#!/usr/bin/env bash
# thisdoes: heredoc based emoji picker
# usage: emoji [list|grep|fzf]
#
# much of the conent is owed to 
# https://github.com/arp242/uni
# https://unicode.org/emoji/charts-13.0/full-emoji-list.html
# http://www.unicode.org/charts/


m1=$1
m2=$2
m3=$3

listemoji() {
	cat <<ENDOFFUCKINGFILE
0️⃣ keycap: 0
1️⃣ keycap: 1
🥇 1st place medal
🥇 1st place medal  Activities
2️⃣ keycap: 2
🥈 2nd place medal
🥈 2nd place medal  Activities
3️⃣ keycap: 3
🥉 3rd place medal
🥉 3rd place medal  Activities
4️⃣ keycap: 4
5️⃣ keycap: 5
6️⃣ keycap: 6
7️⃣ keycap: 7
8️⃣ keycap: 8
9️⃣ keycap: 9
🧮 abacus
🆎 AB button (blood type)
🅰️ A button (blood type)
🩹 adhesive bandage
🎟️ admission tickets
🚡 aerial tramway
✈️ airplane
🛬 airplane arrival
🛫 airplane departure
⏰ alarm clock
⚗️ alembic
👽 alien
👾 alien monster
🚑 ambulance
🏈 american football
🏺 amphora
⚓ anchor
💢 anger symbol
😠 angry face
👿 angry face with horns
😧 anguished face
🐜 ant
📶 antenna bars
😰 anxious face with sweat
♒ Aquarius
♈ Aries
🚛 articulated lorry
🧑‍🎨 artist
🧑🏿‍🎨 artist: dark skin tone
🧑🏻‍🎨 artist: light skin tone
🧑🏾‍🎨 artist: mediumdark skin tone
🧑🏼‍🎨 artist: mediumlight skin tone
🧑🏽‍🎨 artist: medium skin tone
🎨 artist palette
😲 astonished face
🧑‍🚀 astronaut
🧑🏿‍🚀 astronaut: dark skin tone
🧑🏻‍🚀 astronaut: light skin tone
🧑🏾‍🚀 astronaut: mediumdark skin tone
🧑🏼‍🚀 astronaut: mediumlight skin tone
🧑🏽‍🚀 astronaut: medium skin tone
🏧 ATM sign
⚛️ atom symbol
🚗 automobile
🛺 auto rickshaw
🥑 avocado
🪓 axe
👶 baby
👼 baby angel
👼🏿 baby angel: dark skin tone
👼🏻 baby angel: light skin tone
👼🏾 baby angel: mediumdark skin tone
👼🏼 baby angel: mediumlight skin tone
👼🏽 baby angel: medium skin tone
🍼 baby bottle
🐤 baby chick
👶🏿 baby: dark skin tone
👶🏻 baby: light skin tone
👶🏾 baby: mediumdark skin tone
👶🏼 baby: mediumlight skin tone
👶🏽 baby: medium skin tone
🚼 baby symbol
🔙 BACK arrow
👇 backhand index pointing down
👇🏿 backhand index pointing down: dark skin tone
👇🏻 backhand index pointing down: light skin tone
👇🏾 backhand index pointing down: mediumdark skin tone
👇🏼 backhand index pointing down: mediumlight skin tone
👇🏽 backhand index pointing down: medium skin tone
👈 backhand index pointing left
👈🏿 backhand index pointing left: dark skin tone
👈🏻 backhand index pointing left: light skin tone
👈🏾 backhand index pointing left: mediumdark skin tone
👈🏼 backhand index pointing left: mediumlight skin tone
👈🏽 backhand index pointing left: medium skin tone
👉 backhand index pointing right
👉🏿 backhand index pointing right: dark skin tone
👉🏻 backhand index pointing right: light skin tone
👉🏾 backhand index pointing right: mediumdark skin tone
👉🏼 backhand index pointing right: mediumlight skin tone
👉🏽 backhand index pointing right: medium skin tone
👆 backhand index pointing up
👆🏿 backhand index pointing up: dark skin tone
👆🏻 backhand index pointing up: light skin tone
👆🏾 backhand index pointing up: mediumdark skin tone
👆🏼 backhand index pointing up: mediumlight skin tone
👆🏽 backhand index pointing up: medium skin tone
🎒 backpack
🥓 bacon
🦡 badger
🏸 badminton
🥯 bagel
🛄 baggage claim
🥖 baguette bread
⚖️ balance scale
🩰 ballet shoes
🎈 balloon
🗳️ ballot box with ballot
🍌 banana
🪕 banjo
🏦 bank
💈 barber pole
📊 bar chart
⚾ baseball
🧺 basket
🏀 basketball
🦇 bat
🛁 bathtub
🔋 battery
🅱️ B button (blood type)
🏖️ beach with umbrella
😁 beaming face with smiling eyes
🐻 bear
💓 beating heart
🛏️ bed
🍺 beer mug
🔔 bell
🛎️ bellhop bell
🔕 bell with slash
🍱 bento box
🧃 beverage box
🚲 bicycle
👙 bikini
🧢 billed cap
☣️ biohazard
🐦 bird
🎂 birthday cake
⚫ black circle
🏴 black flag
🖤 black heart
⬛ black large square
◾ black medium-small square
◼️ black medium square
✒️ black nib
▪️ black small square
🔲 black square button
🌼 blossom
🐡 blowfish
📘 blue book
🔵 blue circle
💙 blue heart
🟦 blue square
🐗 boar
💣 bomb
🦴 bone
🔖 bookmark
📑 bookmark tabs
📚 books
🍾 bottle with popping cork
💐 bouquet
🏹 bow and arrow
🎳 bowling
🥣 bowl with spoon
🥊 boxing glove
👦 boy
👦🏿 boy: dark skin tone
👦🏻 boy: light skin tone
👦🏾 boy: mediumdark skin tone
👦🏼 boy: mediumlight skin tone
👦🏽 boy: medium skin tone
🧠 brain
🍞 bread
🤱 breast-feeding
🤱🏿 breast-feeding: dark skin tone
🤱🏻 breast-feeding: light skin tone
🤱🏾 breast-feeding: mediumdark skin tone
🤱🏼 breast-feeding: mediumlight skin tone
🤱🏽 breast-feeding: medium skin tone
🧱 brick
👰 bride with veil
👰🏿 bride with veil: dark skin tone
👰🏻 bride with veil: light skin tone
👰🏾 bride with veil: mediumdark skin tone
👰🏼 bride with veil: mediumlight skin tone
👰🏽 bride with veil: medium skin tone
🌉 bridge at night
💼 briefcase
🩲 briefs
🔆 bright button
🥦 broccoli
💔 broken heart
🧹 broom
🟤 brown circle
🤎 brown heart
🟫 brown square
🐛 bug
🏗️ building construction
🚅 bullet train
🌯 burrito
🚌 bus
🚏 bus stop
👤 bust in silhouette
👥 busts in silhouette
🧈 butter
🦋 butterfly
🌵 cactus
📅 calendar
🤙 call me hand
🤙🏿 call me hand: dark skin tone
🤙🏻 call me hand: light skin tone
🤙🏾 call me hand: mediumdark skin tone
🤙🏼 call me hand: mediumlight skin tone
🤙🏽 call me hand: medium skin tone
🐪 camel
📷 camera
📸 camera with flash
🏕️ camping
♋ Cancer
🕯️ candle
🍬 candy
🥫 canned food
🛶 canoe
♑ Capricorn
🗃️ card file box
📇 card index
🗂️ card index dividers
🎠 carousel horse
🎏 carp streamer
🥕 carrot
🏰 castle
🐈 cat
🐱 cat face
😹 cat with tears of joy
😼 cat with wry smile
⛓️ chains
🪑 chair
📉 chart decreasing
📈 chart increasing
💹 chart increasing with yen
☑️ check box with check
✔️ check mark
✅ check mark button
🧀 cheese wedge
🏁 chequered flag
🍒 cherries
🌸 cherry blossom
♟️ chess pawn
🌰 chestnut
🐔 chicken
🧒 child
🧒🏿 child: dark skin tone
🧒🏻 child: light skin tone
🧒🏾 child: mediumdark skin tone
🧒🏼 child: mediumlight skin tone
🧒🏽 child: medium skin tone
🚸 children crossing
🐿️ chipmunk
🍫 chocolate bar
🥢 chopsticks
🎄 Christmas tree
⛪ church
🚬 cigarette
🎦 cinema
Ⓜ️ circled M
🎪 circus tent
🏙️ cityscape
🌆 cityscape at dusk
🗜️ clamp
🎬 clapper board
👏 clapping hands
👏🏿 clapping hands: dark skin tone
👏🏻 clapping hands: light skin tone
👏🏾 clapping hands: mediumdark skin tone
👏🏼 clapping hands: mediumlight skin tone
👏🏽 clapping hands: medium skin tone
🏛️ classical building
🆑 CL button
🍻 clinking beer mugs
🥂 clinking glasses
📋 clipboard
🔃 clockwise vertical arrows
📕 closed book
📪 closed mailbox with lowered flag
📫 closed mailbox with raised flag
🌂 closed umbrella
☁️ cloud
🌩️ cloud with lightning
⛈️ cloud with lightning and rain
🌧️ cloud with rain
🌨️ cloud with snow
🤡 clown face
♣️ club suit
👝 clutch bag
🧥 coat
🍸 cocktail glass
🥥 coconut
⚰️ coffin
🥶 cold face
💥 collision
☄️ comet
🧭 compass
💽 computer disk
🖱️ computer mouse
🎊 confetti ball
😖 confounded face
😕 confused face
🚧 construction
👷 construction worker
👷‍♂️ construction worker
👷🏿 construction worker: dark skin tone
👷🏿‍♂️ construction worker: dark skin tone
👷🏻 construction worker: light skin tone
👷🏻‍♂️ construction worker: light skin tone
👷🏾 construction worker: mediumdark skin tone
👷🏾‍♂️ construction worker: mediumdark skin tone
👷🏼 construction worker: mediumlight skin tone
👷🏼‍♂️ construction worker: mediumlight skin tone
👷🏽 construction worker: medium skin tone
👷🏽‍♂️ construction worker: medium skin tone
🎛️ control knobs
🏪 convenience store
🧑‍🍳 cook
🧑🏿‍🍳 cook: dark skin tone
🍚 cooked rice
🍪 cookie
🍳 cooking
🧑🏻‍🍳 cook: light skin tone
🧑🏾‍🍳 cook: mediumdark skin tone
🧑🏼‍🍳 cook: mediumlight skin tone
🧑🏽‍🍳 cook: medium skin tone
🆒 COOL button
©️ copyright
🛋️ couch and lamp
🔄 counterclockwise arrows button
💑 couple with heart
👨‍❤️‍👨 couple with heart: man, man
👩‍❤️‍👨 couple with heart: woman, man
👩‍❤️‍👩 couple with heart: woman, woman
🐄 cow
🤠 cowboy hat face
🐮 cow face
🦀 crab
🖍️ crayon
💳 credit card
🌙 crescent moon
🦗 cricket
🏏 cricket game
🐊 crocodile
🥐 croissant
🤞 crossed fingers
🤞🏿 crossed fingers: dark skin tone
🤞🏻 crossed fingers: light skin tone
🤞🏾 crossed fingers: mediumdark skin tone
🤞🏼 crossed fingers: mediumlight skin tone
🤞🏽 crossed fingers: medium skin tone
🎌 crossed flags
⚔️ crossed swords
❌ cross mark
❎ cross mark button
👑 crown
😿 crying cat
😢 crying face
🔮 crystal ball
🥒 cucumber
🧁 cupcake
🥤 cup with straw
🥌 curling stone
➰ curly loop
💱 currency exchange
🍛 curry rice
🍮 custard
🛃 customs
🥩 cut of meat
🌀 cyclone
🗡️ dagger
🍡 dango
💨 dashing away
🧏‍♂️ deaf man
🧏🏿‍♂️ deaf man: dark skin tone
🧏🏻‍♂️ deaf man: light skin tone
🧏🏾‍♂️ deaf man: mediumdark skin tone
🧏🏼‍♂️ deaf man: mediumlight skin tone
🧏🏽‍♂️ deaf man: medium skin tone
🧏 deaf person
🧏🏿 deaf person: dark skin tone
🧏🏻 deaf person: light skin tone
🧏🏾 deaf person: mediumdark skin tone
🧏🏼 deaf person: mediumlight skin tone
🧏🏽 deaf person: medium skin tone
🧏‍♀️ deaf woman
🧏🏿‍♀️ deaf woman: dark skin tone
🧏🏻‍♀️ deaf woman: light skin tone
🧏🏾‍♀️ deaf woman: mediumdark skin tone
🧏🏼‍♀️ deaf woman: mediumlight skin tone
🧏🏽‍♀️ deaf woman: medium skin tone
🌳 deciduous tree
🦌 deer
🚚 delivery truck
🏬 department store
🏚️ derelict house
🏜️ desert
🏝️ desert island
🖥️ desktop computer
🕵️ detective
🕵️‍♂️ detective
🕵🏿 detective: dark skin tone
🕵🏿‍♂️ detective: dark skin tone
🕵🏻 detective: light skin tone
🕵🏻‍♂️ detective: light skin tone
🕵🏾 detective: mediumdark skin tone
🕵🏾‍♂️ detective: mediumdark skin tone
🕵🏼 detective: mediumlight skin tone
🕵🏼‍♂️ detective: mediumlight skin tone
🕵🏽 detective: medium skin tone
🕵🏽‍♂️ detective: medium skin tone
♦️ diamond suit
💠 diamond with a dot
🔅 dim button
🎯 direct hit
😞 disappointed face
🤿 diving mask
➗ division sign
🪔 diya lamp
💫 dizzy
😵 dizzy face
🧬 dna
🐕 dog
🐶 dog face
💵 dollar banknote
🐬 dolphin
🚪 door
🔯 dotted six-pointed star
➿ double curly loop
‼️ double exclamation mark
🍩 doughnut
🕊️ dove
⬇️ down arrow
😓 downcast face with sweat
↙️ down-left arrow
↘️ down-right arrow
🔽 downwards button
🐉 dragon
🐲 dragon face
👗 dress
🤤 drooling face
💧 droplet
🩸 drop of blood
🥁 drum
🦆 duck
🥟 dumpling
📀 dvd
🦅 eagle
👂 ear
👂🏿 ear: dark skin tone
👂🏻 ear: light skin tone
👂🏾 ear: mediumdark skin tone
👂🏼 ear: mediumlight skin tone
👂🏽 ear: medium skin tone
🌽 ear of corn
🦻 ear with hearing aid
🦻🏿 ear with hearing aid: dark skin tone
🦻🏻 ear with hearing aid: light skin tone
🦻🏾 ear with hearing aid: mediumdark skin tone
🦻🏼 ear with hearing aid: mediumlight skin tone
🦻🏽 ear with hearing aid: medium skin tone
🥚 egg
🍆 eggplant
🕗 eight o’clock
✴️ eight-pointed star
✳️ eight-spoked asterisk
🕣 eight-thirty
⏏️ eject button
🔌 electric plug
🐘 elephant
🕚 eleven o’clock
🕦 eleven-thirty
🧝 elf
🧝‍♂️ elf
🧝🏿 elf: dark skin tone
🧝🏿‍♂️ elf: dark skin tone
🧝🏻 elf: light skin tone
🧝🏻‍♂️ elf: light skin tone
🧝🏾 elf: mediumdark skin tone
🧝🏾‍♂️ elf: mediumdark skin tone
🧝🏼 elf: mediumlight skin tone
🧝🏼‍♂️ elf: mediumlight skin tone
🧝🏽 elf: medium skin tone
🧝🏽‍♂️ elf: medium skin tone
📧 e-mail
🔚 END arrow
✉️ envelope
📩 envelope with arrow
💶 euro banknote
🌲 evergreen tree
🐑 ewe
❗ exclamation mark
⁉️ exclamation question mark
⁉️ exclamation question mark    Symbols
🤯 exploding head
😑 expressionless face
👁️ eye
👁️‍🗨️ eye in speech bubble
👀 eyes
😘 face blowing a kiss
😋 face savoring food
😱 face screaming in fear
🤮 face vomiting
🤭 face with hand over mouth
🤕 face with head-bandage
😷 face with medical mask
🧐 face with monocle
😮 face with open mouth
😶 face without mouth
🤨 face with raised eyebrow
🙄 face with rolling eyes
😤 face with steam from nose
🤬 face with symbols on mouth
😂 face with tears of joy
🤒 face with thermometer
😛 face with tongue
🏭 factory
🧑‍🏭 factory worker
🧑🏿‍🏭 factory worker: dark skin tone
🧑🏻‍🏭 factory worker: light skin tone
🧑🏾‍🏭 factory worker: mediumdark skin tone
🧑🏼‍🏭 factory worker: mediumlight skin tone
🧑🏽‍🏭 factory worker: medium skin tone
🧚 fairy
🧚‍♂️ fairy
🧚🏿 fairy: dark skin tone
🧚🏿‍♂️ fairy: dark skin tone
🧚🏻 fairy: light skin tone
🧚🏻‍♂️ fairy: light skin tone
🧚🏾 fairy: mediumdark skin tone
🧚🏾‍♂️ fairy: mediumdark skin tone
🧚🏼 fairy: mediumlight skin tone
🧚🏼‍♂️ fairy: mediumlight skin tone
🧚🏽 fairy: medium skin tone
🧚🏽‍♂️ fairy: medium skin tone
🧆 falafel
🍂 fallen leaf
👪 family
👨‍👦 family: man, boy
👨‍👦‍👦 family: man, boy, boy
👨‍👧 family: man, girl
👨‍👧‍👦 family: man, girl, boy
👨‍👧‍👧 family: man, girl, girl
👨‍👨‍👦 family: man, man, boy
👨‍👨‍👦‍👦 family: man, man, boy, boy
👨‍👨‍👧 family: man, man, girl
👨‍👨‍👧‍👦 family: man, man, girl, boy
👨‍👨‍👧‍👧 family: man, man, girl, girl
👨‍👩‍👦 family: man, woman, boy
👨‍👩‍👦‍👦 family: man, woman, boy, boy
👨‍👩‍👧 family: man, woman, girl
👨‍👩‍👧‍👦 family: man, woman, girl, boy
👨‍👩‍👧‍👧 family: man, woman, girl, girl
👩‍👦 family: woman, boy
👩‍👦‍👦 family: woman, boy, boy
👩‍👧 family: woman, girl
👩‍👧‍👦 family: woman, girl, boy
👩‍👧‍👧 family: woman, girl, girl
👩‍👩‍👦 family: woman, woman, boy
👩‍👩‍👦‍👦 family: woman, woman, boy, boy
👩‍👩‍👧 family: woman, woman, girl
👩‍👩‍👧‍👦 family: woman, woman, girl, boy
👩‍👩‍👧‍👧 family: woman, woman, girl, girl
🧑‍🌾 farmer
🧑🏿‍🌾 farmer: dark skin tone
🧑🏻‍🌾 farmer: light skin tone
🧑🏾‍🌾 farmer: mediumdark skin tone
🧑🏼‍🌾 farmer: mediumlight skin tone
🧑🏽‍🌾 farmer: medium skin tone
⏬ fast down button
⏩ fast-forward button
⏪ fast reverse button
⏫ fast up button
📠 fax machine
😨 fearful face
♀️ female sign
🎡 ferris wheel
⛴️ ferry
🏑 field hockey
🗄️ file cabinet
📁 file folder
🎞️ film frames
📽️ film projector
🔥 fire
🧨 firecracker
🚒 fire engine
🧯 fire extinguisher
🧑‍🚒 firefighter
🧑🏿‍🚒 firefighter: dark skin tone
🧑🏻‍🚒 firefighter: light skin tone
🧑🏾‍🚒 firefighter: mediumdark skin tone
🧑🏼‍🚒 firefighter: mediumlight skin tone
🧑🏽‍🚒 firefighter: medium skin tone
🎆 fireworks
🌓 first quarter moon
🌛 first quarter moon face
🐟 fish
🍥 fish cake with swirl
🎣 fishing pole
🕔 five o’clock
🕠 five-thirty
🇦🇫 flag: Afghanistan
🇦🇽 flag: Åland Islands
🇦🇱 flag: Albania
🇩🇿 flag: Algeria
🇦🇸 flag: American Samoa
🇦🇩 flag: Andorra
🇦🇴 flag: Angola
🇦🇮 flag: Anguilla
🇦🇶 flag: Antarctica
🇦🇬 flag: Antigua & Barbuda
🇦🇷 flag: Argentina
🇦🇲 flag: Armenia
🇦🇼 flag: Aruba
🇦🇨 flag: Ascension Island
🇦🇺 flag: Australia
🇦🇹 flag: Austria
🇦🇿 flag: Azerbaijan
🇧🇸 flag: Bahamas
🇧🇭 flag: Bahrain
🇧🇩 flag: Bangladesh
🇧🇧 flag: Barbados
🇧🇾 flag: Belarus
🇧🇪 flag: Belgium
🇧🇿 flag: Belize
🇧🇯 flag: Benin
🇧🇲 flag: Bermuda
🇧🇹 flag: Bhutan
🇧🇴 flag: Bolivia
🇧🇦 flag: Bosnia & Herzegovina
🇧🇼 flag: Botswana
🇧🇻 flag: Bouvet Island
🇧🇷 flag: Brazil
🇮🇴 flag: British Indian Ocean Territory
🇻🇬 flag: British Virgin Islands
🇧🇳 flag: Brunei
🇧🇬 flag: Bulgaria
🇧🇫 flag: Burkina Faso
🇧🇮 flag: Burundi
🇰🇭 flag: Cambodia
🇨🇲 flag: Cameroon
🇨🇦 flag: Canada
🇮🇨 flag: Canary Islands
🇨🇻 flag: Cape Verde
🇧🇶 flag: Caribbean Netherlands
🇰🇾 flag: Cayman Islands
🇨🇫 flag: Central African Republic
🇪🇦 flag: Ceuta & Melilla
🇹🇩 flag: Chad
🇨🇱 flag: Chile
🇨🇳 flag: China
🇨🇽 flag: Christmas Island
🇨🇵 flag: Clipperton Island
🇨🇨 flag: Cocos (Keeling) Islands
🇨🇴 flag: Colombia
🇰🇲 flag: Comoros
🇨🇬 flag: Congo - Brazzaville
🇨🇩 flag: Congo - Kinshasa
🇨🇰 flag: Cook Islands
🇨🇷 flag: Costa Rica
🇨🇮 flag: Côte d’Ivoire
🇭🇷 flag: Croatia
🇨🇺 flag: Cuba
🇨🇼 flag: Curaçao
🇨🇾 flag: Cyprus
🇨🇿 flag: Czechia
🇩🇰 flag: Denmark
🇩🇬 flag: Diego Garcia
🇩🇯 flag: Djibouti
🇩🇲 flag: Dominica
🇩🇴 flag: Dominican Republic
🇪🇨 flag: Ecuador
🇪🇬 flag: Egypt
🇸🇻 flag: El Salvador
🏴󠁧󠁢󠁥󠁮󠁧󠁿 flag: England
🇬🇶 flag: Equatorial Guinea
🇪🇷 flag: Eritrea
🇪🇪 flag: Estonia
🇸🇿 flag: Eswatini
🇪🇹 flag: Ethiopia
🇪🇺 flag: European Union
🇫🇰 flag: Falkland Islands
🇫🇴 flag: Faroe Islands
🇫🇯 flag: Fiji
🇫🇮 flag: Finland
🇫🇷 flag: France
🇬🇫 flag: French Guiana
🇵🇫 flag: French Polynesia
🇹🇫 flag: French Southern Territories
🇬🇦 flag: Gabon
🇬🇲 flag: Gambia
🇬🇪 flag: Georgia
🇩🇪 flag: Germany
🇬🇭 flag: Ghana
🇬🇮 flag: Gibraltar
🇬🇷 flag: Greece
🇬🇱 flag: Greenland
🇬🇩 flag: Grenada
🇬🇵 flag: Guadeloupe
🇬🇺 flag: Guam
🇬🇹 flag: Guatemala
🇬🇬 flag: Guernsey
🇬🇳 flag: Guinea
🇬🇼 flag: Guinea-Bissau
🇬🇾 flag: Guyana
🇭🇹 flag: Haiti
🇭🇲 flag: Heard & McDonald Islands
🇭🇳 flag: Honduras
🇭🇰 flag: Hong Kong SAR China
🇭🇺 flag: Hungary
🇮🇸 flag: Iceland
🇮🇳 flag: India
🇮🇩 flag: Indonesia
⛳ flag in hole
🇮🇷 flag: Iran
🇮🇶 flag: Iraq
🇮🇪 flag: Ireland
🇮🇲 flag: Isle of Man
🇮🇱 flag: Israel
🇮🇹 flag: Italy
🇯🇲 flag: Jamaica
🇯🇵 flag: Japan
🇯🇪 flag: Jersey
🇯🇴 flag: Jordan
🇰🇿 flag: Kazakhstan
🇰🇪 flag: Kenya
🇰🇮 flag: Kiribati
🇽🇰 flag: Kosovo
🇰🇼 flag: Kuwait
🇰🇬 flag: Kyrgyzstan
🇱🇦 flag: Laos
🇱🇻 flag: Latvia
🇱🇧 flag: Lebanon
🇱🇸 flag: Lesotho
🇱🇷 flag: Liberia
🇱🇾 flag: Libya
🇱🇮 flag: Liechtenstein
🇱🇹 flag: Lithuania
🇱🇺 flag: Luxembourg
🇲🇴 flag: Macao SAR China
🇲🇬 flag: Madagascar
🇲🇼 flag: Malawi
🇲🇾 flag: Malaysia
🇲🇻 flag: Maldives
🇲🇱 flag: Mali
🇲🇹 flag: Malta
🇲🇭 flag: Marshall Islands
🇲🇶 flag: Martinique
🇲🇷 flag: Mauritania
🇲🇺 flag: Mauritius
🇾🇹 flag: Mayotte
🇲🇽 flag: Mexico
🇫🇲 flag: Micronesia
🇲🇩 flag: Moldova
🇲🇨 flag: Monaco
🇲🇳 flag: Mongolia
🇲🇪 flag: Montenegro
🇲🇸 flag: Montserrat
🇲🇦 flag: Morocco
🇲🇿 flag: Mozambique
🇲🇲 flag: Myanmar (Burma)
🇳🇦 flag: Namibia
🇳🇷 flag: Nauru
🇳🇵 flag: Nepal
🇳🇱 flag: Netherlands
🇳🇨 flag: New Caledonia
🇳🇿 flag: New Zealand
🇳🇮 flag: Nicaragua
🇳🇪 flag: Niger
🇳🇬 flag: Nigeria
🇳🇺 flag: Niue
🇳🇫 flag: Norfolk Island
🇲🇵 flag: Northern Mariana Islands
🇰🇵 flag: North Korea
🇲🇰 flag: North Macedonia
🇳🇴 flag: Norway
🇴🇲 flag: Oman
🇵🇰 flag: Pakistan
🇵🇼 flag: Palau
🇵🇸 flag: Palestinian Territories
🇵🇦 flag: Panama
🇵🇬 flag: Papua New Guinea
🇵🇾 flag: Paraguay
🇵🇪 flag: Peru
🇵🇭 flag: Philippines
🇵🇳 flag: Pitcairn Islands
🇵🇱 flag: Poland
🇵🇹 flag: Portugal
🇵🇷 flag: Puerto Rico
🇶🇦 flag: Qatar
🇷🇪 flag: Réunion
🇷🇴 flag: Romania
🇷🇺 flag: Russia
🇷🇼 flag: Rwanda
🇼🇸 flag: Samoa
🇸🇲 flag: San Marino
🇸🇹 flag: São Tomé & Príncipe
🇸🇦 flag: Saudi Arabia
🏴󠁧󠁢󠁳󠁣󠁴󠁿 flag: Scotland
🇸🇳 flag: Senegal
🇷🇸 flag: Serbia
🇸🇨 flag: Seychelles
🇸🇱 flag: Sierra Leone
🇸🇬 flag: Singapore
🇸🇽 flag: Sint Maarten
🇸🇰 flag: Slovakia
🇸🇮 flag: Slovenia
🇸🇧 flag: Solomon Islands
🇸🇴 flag: Somalia
🇿🇦 flag: South Africa
🇬🇸 flag: South Georgia & South Sandwich Islands
🇰🇷 flag: South Korea
🇸🇸 flag: South Sudan
🇪🇸 flag: Spain
🇱🇰 flag: Sri Lanka
🇧🇱 flag: St. Barthélemy
🇸🇭 flag: St. Helena
🇰🇳 flag: St. Kitts & Nevis
🇱🇨 flag: St. Lucia
🇲🇫 flag: St. Martin
🇵🇲 flag: St. Pierre & Miquelon
🇻🇨 flag: St. Vincent & Grenadines
🇸🇩 flag: Sudan
🇸🇷 flag: Suriname
🇸🇯 flag: Svalbard & Jan Mayen
🇸🇪 flag: Sweden
🇨🇭 flag: Switzerland
🇸🇾 flag: Syria
🇹🇼 flag: Taiwan
🇹🇯 flag: Tajikistan
🇹🇿 flag: Tanzania
🇹🇭 flag: Thailand
🇹🇱 flag: Timor-Leste
🇹🇬 flag: Togo
🇹🇰 flag: Tokelau
🇹🇴 flag: Tonga
🇹🇹 flag: Trinidad & Tobago
🇹🇦 flag: Tristan da Cunha
🇹🇳 flag: Tunisia
🇹🇷 flag: Turkey
🇹🇲 flag: Turkmenistan
🇹🇨 flag: Turks & Caicos Islands
🇹🇻 flag: Tuvalu
🇺🇬 flag: Uganda
🇺🇦 flag: Ukraine
🇦🇪 flag: United Arab Emirates
🇬🇧 flag: United Kingdom
🇺🇳 flag: United Nations
🇺🇸 flag: United States
🇺🇾 flag: Uruguay
🇺🇲 flag: U.S. Outlying Islands
🇻🇮 flag: U.S. Virgin Islands
🇺🇿 flag: Uzbekistan
🇻🇺 flag: Vanuatu
🇻🇦 flag: Vatican City
🇻🇪 flag: Venezuela
🇻🇳 flag: Vietnam
🏴󠁧󠁢󠁷󠁬󠁳󠁿 flag: Wales
🇼🇫 flag: Wallis & Futuna
🇪🇭 flag: Western Sahara
🇾🇪 flag: Yemen
🇿🇲 flag: Zambia
🇿🇼 flag: Zimbabwe
🦩 flamingo
🔦 flashlight
🥿 flat shoe
⚜️ fleur-de-lis
💪 flexed biceps
💪🏿 flexed biceps: dark skin tone
💪🏻 flexed biceps: light skin tone
💪🏾 flexed biceps: mediumdark skin tone
💪🏼 flexed biceps: mediumlight skin tone
💪🏽 flexed biceps: medium skin tone
💾 floppy disk
🎴 flower playing cards
😳 flushed face
🥏 flying disc
🛸 flying saucer
🌫️ fog
🌁 foggy
🙏 folded hands
🙏🏿 folded hands: dark skin tone
🙏🏻 folded hands: light skin tone
🙏🏾 folded hands: mediumdark skin tone
🙏🏼 folded hands: mediumlight skin tone
🙏🏽 folded hands: medium skin tone
🦶 foot
🦶🏿 foot: dark skin tone
🦶🏻 foot: light skin tone
🦶🏾 foot: mediumdark skin tone
🦶🏼 foot: mediumlight skin tone
🦶🏽 foot: medium skin tone
👣 footprints
🍴 fork and knife
🍽️ fork and knife with plate
🥠 fortune cookie
⛲ fountain
🖋️ fountain pen
🍀 four leaf clover
🕓 four o’clock
🕟 four-thirty
🦊 fox
🖼️ framed picture
🆓 FREE button
🍟 french fries
🍤 fried shrimp
🐸 frog
🐥 front-facing baby chick
☹️ frowning face
😦 frowning face with open mouth
⛽ fuel pump
🌕 full moon
🌝 full moon face
⚱️ funeral urn
🎲 game die
🧄 garlic
⚙️ gear
♊ Gemini
💎 gem stone
🧞 genie
🧞‍♂️ genie
👻 ghost
🦒 giraffe
👧 girl
👧🏿 girl: dark skin tone
👧🏻 girl: light skin tone
👧🏾 girl: mediumdark skin tone
👧🏼 girl: mediumlight skin tone
👧🏽 girl: medium skin tone
👓 glasses
🥛 glass of milk
🌎 globe showing Americas
🌏 globe showing Asia-Australia
🌍 globe showing Europe-Africa
🌐 globe with meridians
🧤 gloves
🌟 glowing star
🥅 goal net
🐐 goat
👺 goblin
🥽 goggles
🦍 gorilla
🎓 graduation cap
🍇 grapes
🍏 green apple
📗 green book
🟢 green circle
💚 green heart
🥗 green salad
🟩 green square
😬 grimacing face
😺 grinning cat
😸 grinning cat with smiling eyes
😀 grinning face
😃 grinning face with big eyes
😄 grinning face with smiling eyes
😅 grinning face with sweat
😆 grinning squinting face
💗 growing heart
💂 guard
💂‍♂️ guard
💂🏿 guard: dark skin tone
💂🏿‍♂️ guard: dark skin tone
💂🏻 guard: light skin tone
💂🏻‍♂️ guard: light skin tone
💂🏾 guard: mediumdark skin tone
💂🏾‍♂️ guard: mediumdark skin tone
💂🏼 guard: mediumlight skin tone
💂🏼‍♂️ guard: mediumlight skin tone
💂🏽 guard: medium skin tone
💂🏽‍♂️ guard: medium skin tone
🦮 guide dog
🎸 guitar
🍔 hamburger
🔨 hammer
⚒️ hammer and pick
🛠️ hammer and wrench
🐹 hamster
👜 handbag
🤝 handshake
🖐️ hand with fingers splayed
🖐🏿 hand with fingers splayed: dark skin tone
🖐🏻 hand with fingers splayed: light skin tone
🖐🏾 hand with fingers splayed: mediumdark skin tone
🖐🏼 hand with fingers splayed: mediumlight skin tone
🖐🏽 hand with fingers splayed: medium skin tone
🐣 hatching chick
🎧 headphone
🧑‍⚕️ health worker
🧑🏿‍⚕ health worker: dark skin tone
🧑🏻‍⚕ health worker: light skin tone
🧑🏾‍⚕ health worker: mediumdark skin tone
🧑🏼‍⚕ health worker: mediumlight skin tone
🧑🏽‍⚕ health worker: medium skin tone
🙉 hear-no-evil monkey
💟 heart decoration
❣️ heart exclamation
♥️ heart suit
💘 heart with arrow
💝 heart with ribbon
💲 heavy dollar sign
🦔 hedgehog
🚁 helicopter
🌿 herb
🌺 hibiscus
👠 high-heeled shoe
🚄 high-speed train
⚡ high voltage
🥾 hiking boot
🛕 hindu temple
🦛 hippopotamus
🕳️ hole
⭕ hollow red circle
🐝 honeybee
🍯 honey pot
🚥 horizontal traffic light
🐎 horse
🐴 horse face
🏇 horse racing
🏇🏿 horse racing: dark skin tone
🏇🏻 horse racing: light skin tone
🏇🏾 horse racing: mediumdark skin tone
🏇🏼 horse racing: mediumlight skin tone
🏇🏽 horse racing: medium skin tone
🏥 hospital
☕ hot beverage
🌭 hot dog
🏨 hotel
🥵 hot face
🌶️ hot pepper
♨️ hot springs
⌛ hourglass done
⏳ hourglass not done
🏠 house
🏘️ houses
🏡 house with garden
🤗 hugging face
💯 hundred points
😯 hushed face
🧊 ice
🍨 ice cream
🏒 ice hockey
⛸️ ice skate
🆔 ID button
📥 inbox tray
📨 incoming envelope
☝️ index pointing up
☝🏿 index pointing up: dark skin tone
☝🏻 index pointing up: light skin tone
☝🏾 index pointing up: mediumdark skin tone
☝🏼 index pointing up: mediumlight skin tone
☝🏽 index pointing up: medium skin tone
♾️ infinity
ℹ️ information
🔤 input latin letters
🔡 input latin lowercase
🔠 input latin uppercase
🔢 input numbers
🔣 input symbols
🎃 jack-o-lantern
🉑 Japanese “acceptable” button
🈸 Japanese “application” button
🉐 Japanese “bargain” button
🏯 Japanese castle
㊗️ Japanese “congratulations” button
🈹 Japanese “discount” button
🎎 Japanese dolls
🈚 Japanese “free of charge” button
🈁 Japanese “here” button
🈷️ Japanese “monthly amount” button
🈶 Japanese “not free of charge” button
🈵 Japanese “no vacancy” button
🈺 Japanese “open for business” button
🈴 Japanese “passing grade” button
🏣 Japanese post office
🈲 Japanese “prohibited” button
🈯 Japanese “reserved” button
㊙️ Japanese “secret” button
🈂️ Japanese “service charge” button
🔰 Japanese symbol for beginner
🈳 Japanese “vacancy” button
👖 jeans
🃏 joker
🕹️ joystick
🧑‍⚖️ judge
🧑🏿‍⚖ judge: dark skin tone
🧑🏻‍⚖ judge: light skin tone
🧑🏾‍⚖ judge: mediumdark skin tone
🧑🏼‍⚖ judge: mediumlight skin tone
🧑🏽‍⚖ judge: medium skin tone
🕋 kaaba
🦘 kangaroo
🔑 key
⌨️ keyboard
*️⃣ keycap: *
#️⃣ keycap: #
🔟 keycap: 10
🛴 kick scooter
👘 kimono
💏 kiss
😽 kissing cat
😗 kissing face
😚 kissing face with closed eyes
😙 kissing face with smiling eyes
👨‍❤️‍💋‍👨 kiss: man, man
💋 kiss mark
👩‍❤️‍💋‍👨 kiss: woman, man
👩‍❤️‍💋‍👩 kiss: woman, woman
🔪 kitchen knife
🪁 kite
🥝 kiwi fruit
🐨 koala
🥼 lab coat
🏷️ label
🥍 lacrosse
🐞 lady beetle
💻 laptop
🔷 large blue diamond
🔶 large orange diamond
🌗 last quarter moon
🌜 last quarter moon face
⏮️ last track button
✝️ latin cross
🍃 leaf fluttering in wind
🥬 leafy green
📒 ledger
⬅️ left arrow
↪️ left arrow curving right
🤛 left-facing fist
🤛🏿 left-facing fist: dark skin tone
🤛🏻 left-facing fist: light skin tone
🤛🏾 left-facing fist: mediumdark skin tone
🤛🏼 left-facing fist: mediumlight skin tone
🤛🏽 left-facing fist: medium skin tone
🛅 left luggage
↔️ left-right arrow
🗨️ left speech bubble
🦵 leg
🦵🏿 leg: dark skin tone
🦵🏻 leg: light skin tone
🦵🏾 leg: mediumdark skin tone
🦵🏼 leg: mediumlight skin tone
🦵🏽 leg: medium skin tone
🍋 lemon
♌ Leo
🐆 leopard
🎚️ level slider
♎ Libra
💡 light bulb
🚈 light rail
🔗 link
🖇️ linked paperclips
🦁 lion
💄 lipstick
🚮 litter in bin sign
🦎 lizard
🦙 llama
🦞 lobster
🔒 locked
🔐 locked with key
🔏 locked with pen
🚂 locomotive
🍭 lollipop
🧴 lotion bottle
😭 loudly crying face
📢 loudspeaker
🏩 love hotel
💌 love letter
🤟 love-you gesture
🤟🏿 love-you gesture: dark skin tone
🤟🏻 love-you gesture: light skin tone
🤟🏾 love-you gesture: mediumdark skin tone
🤟🏼 love-you gesture: mediumlight skin tone
🤟🏽 love-you gesture: medium skin tone
🧳 luggage
🤥 lying face
🧙 mage
🧙‍♂️ mage
🧙🏿 mage: dark skin tone
🧙🏿‍♂️ mage: dark skin tone
🧙🏻 mage: light skin tone
🧙🏻‍♂️ mage: light skin tone
🧙🏾 mage: mediumdark skin tone
🧙🏾‍♂️ mage: mediumdark skin tone
🧙🏼 mage: mediumlight skin tone
🧙🏼‍♂️ mage: mediumlight skin tone
🧙🏽 mage: medium skin tone
🧙🏽‍♂️ mage: medium skin tone
🧲 magnet
🔍 magnifying glass tilted left
🔎 magnifying glass tilted right
🀄 mahjong red dragon
♂️ male sign
👨 man
👨‍🎨 man artist
👨🏿‍🎨 man artist: dark skin tone
👨🏻‍🎨 man artist: light skin tone
👨🏾‍🎨 man artist: mediumdark skin tone
👨🏼‍🎨 man artist: mediumlight skin tone
👨🏽‍🎨 man artist: medium skin tone
👨‍🚀 man astronaut
👨🏿‍🚀 man astronaut: dark skin tone
👨🏻‍🚀 man astronaut: light skin tone
👨🏾‍🚀 man astronaut: mediumdark skin tone
👨🏼‍🚀 man astronaut: mediumlight skin tone
👨🏽‍🚀 man astronaut: medium skin tone
👨‍🦲 man: bald
👨🏿‍🦲 man: bald: dark skin tone
👨🏻‍🦲 man: bald: light skin tone
👨🏾‍🦲 man: bald: mediumdark skin tone
👨🏼‍🦲 man: bald: mediumlight skin tone
👨🏽‍🦲 man: bald: medium skin tone
🧔 man: beard
🧔🏿 man: beard: dark skin tone
🧔🏻 man: beard: light skin tone
🧔🏾 man: beard: mediumdark skin tone
🧔🏼 man: beard: mediumlight skin tone
🧔🏽 man: beard: medium skin tone
🚴‍♂️ man biking
🚴🏿‍♂️ man biking: dark skin tone
🚴🏻‍♂️ man biking: light skin tone
🚴🏾‍♂️ man biking: mediumdark skin tone
🚴🏼‍♂️ man biking: mediumlight skin tone
🚴🏽‍♂️ man biking: medium skin tone
👱‍♂️ man: blond hair
👱🏿‍♂️ man: blond hair: dark skin tone
👱🏻‍♂️ man: blond hair: light skin tone
👱🏾‍♂️ man: blond hair: mediumdark skin tone
👱🏼‍♂️ man: blond hair: mediumlight skin tone
👱🏽‍♂️ man: blond hair: medium skin tone
⛹️‍♂️ man bouncing ball
⛹🏿‍♂️ man bouncing ball: dark skin tone
⛹🏻‍♂️ man bouncing ball: light skin tone
⛹🏾‍♂️ man bouncing ball: mediumdark skin tone
⛹🏼‍♂️ man bouncing ball: mediumlight skin tone
⛹🏽‍♂️ man bouncing ball: medium skin tone
🙇‍♂️ man bowing
🙇🏿‍♂️ man bowing: dark skin tone
🙇🏻‍♂️ man bowing: light skin tone
🙇🏾‍♂️ man bowing: mediumdark skin tone
🙇🏼‍♂️ man bowing: mediumlight skin tone
🙇🏽‍♂️ man bowing: medium skin tone
🤸‍♂️ man cartwheeling
🤸🏿‍♂️ man cartwheeling: dark skin tone
🤸🏻‍♂️ man cartwheeling: light skin tone
🤸🏾‍♂️ man cartwheeling: mediumdark skin tone
🤸🏼‍♂️ man cartwheeling: mediumlight skin tone
🤸🏽‍♂️ man cartwheeling: medium skin tone
🧗‍♂️ man climbing
🧗🏿‍♂️ man climbing: dark skin tone
🧗🏻‍♂️ man climbing: light skin tone
🧗🏾‍♂️ man climbing: mediumdark skin tone
🧗🏼‍♂️ man climbing: mediumlight skin tone
🧗🏽‍♂️ man climbing: medium skin tone
👨‍🍳 man cook
👨🏿‍🍳 man cook: dark skin tone
👨🏻‍🍳 man cook: light skin tone
👨🏾‍🍳 man cook: mediumdark skin tone
👨🏼‍🍳 man cook: mediumlight skin tone
👨🏽‍🍳 man cook: medium skin tone
👨‍🦱 man: curly hair
👨🏿‍🦱 man: curly hair: dark skin tone
👨🏻‍🦱 man: curly hair: light skin tone
👨🏾‍🦱 man: curly hair: mediumdark skin tone
👨🏼‍🦱 man: curly hair: mediumlight skin tone
👨🏽‍🦱 man: curly hair: medium skin tone
🕺 man dancing
🕺🏿 man dancing: dark skin tone
🕺🏻 man dancing: light skin tone
🕺🏾 man dancing: mediumdark skin tone
🕺🏼 man dancing: mediumlight skin tone
🕺🏽 man dancing: medium skin tone
👨🏿 man: dark skin tone
🤦‍♂️ man facepalming
🤦🏿‍♂️ man facepalming: dark skin tone
🤦🏻‍♂️ man facepalming: light skin tone
🤦🏾‍♂️ man facepalming: mediumdark skin tone
🤦🏼‍♂️ man facepalming: mediumlight skin tone
🤦🏽‍♂️ man facepalming: medium skin tone
👨‍🏭 man factory worker
👨🏿‍🏭 man factory worker: dark skin tone
👨🏻‍🏭 man factory worker: light skin tone
👨🏾‍🏭 man factory worker: mediumdark skin tone
👨🏼‍🏭 man factory worker: mediumlight skin tone
👨🏽‍🏭 man factory worker: medium skin tone
👨‍🌾 man farmer
👨🏿‍🌾 man farmer: dark skin tone
👨🏻‍🌾 man farmer: light skin tone
👨🏾‍🌾 man farmer: mediumdark skin tone
👨🏼‍🌾 man farmer: mediumlight skin tone
👨🏽‍🌾 man farmer: medium skin tone
👨‍🚒 man firefighter
👨🏿‍🚒 man firefighter: dark skin tone
👨🏻‍🚒 man firefighter: light skin tone
👨🏾‍🚒 man firefighter: mediumdark skin tone
👨🏼‍🚒 man firefighter: mediumlight skin tone
👨🏽‍🚒 man firefighter: medium skin tone
🙍‍♂️ man frowning
🙍🏿‍♂️ man frowning: dark skin tone
🙍🏻‍♂️ man frowning: light skin tone
🙍🏾‍♂️ man frowning: mediumdark skin tone
🙍🏼‍♂️ man frowning: mediumlight skin tone
🙍🏽‍♂️ man frowning: medium skin tone
🙅‍♂️ man gesturing NO
🙅🏿‍♂️ man gesturing NO: dark skin tone
🙅🏻‍♂️ man gesturing NO: light skin tone
🙅🏾‍♂️ man gesturing NO: mediumdark skin tone
🙅🏼‍♂️ man gesturing NO: mediumlight skin tone
🙅🏽‍♂️ man gesturing NO: medium skin tone
🙆‍♂️ man gesturing OK
🙆🏿‍♂️ man gesturing OK: dark skin tone
🙆🏻‍♂️ man gesturing OK: light skin tone
🙆🏾‍♂️ man gesturing OK: mediumdark skin tone
🙆🏼‍♂️ man gesturing OK: mediumlight skin tone
🙆🏽‍♂️ man gesturing OK: medium skin tone
💇‍♂️ man getting haircut
💇🏿‍♂️ man getting haircut: dark skin tone
💇🏻‍♂️ man getting haircut: light skin tone
💇🏾‍♂️ man getting haircut: mediumdark skin tone
💇🏼‍♂️ man getting haircut: mediumlight skin tone
💇🏽‍♂️ man getting haircut: medium skin tone
💆‍♂️ man getting massage
💆🏿‍♂️ man getting massage: dark skin tone
💆🏻‍♂️ man getting massage: light skin tone
💆🏾‍♂️ man getting massage: mediumdark skin tone
💆🏼‍♂️ man getting massage: mediumlight skin tone
💆🏽‍♂️ man getting massage: medium skin tone
🥭 mango
🏌️‍♂️ man golfing
🏌🏿‍♂️ man golfing: dark skin tone
🏌🏻‍♂️ man golfing: light skin tone
🏌🏾‍♂️ man golfing: mediumdark skin tone
🏌🏼‍♂️ man golfing: mediumlight skin tone
🏌🏽‍♂️ man golfing: medium skin tone
👨‍⚕️ man health worker
👨🏿‍⚕ man health worker: dark skin tone
👨🏻‍⚕ man health worker: light skin tone
👨🏾‍⚕ man health worker: mediumdark skin tone
👨🏼‍⚕ man health worker: mediumlight skin tone
👨🏽‍⚕ man health worker: medium skin tone
🧘‍♂️ man in lotus position
🧘🏿‍♂️ man in lotus position: dark skin tone
🧘🏻‍♂️ man in lotus position: light skin tone
🧘🏾‍♂️ man in lotus position: mediumdark skin tone
🧘🏼‍♂️ man in lotus position: mediumlight skin tone
🧘🏽‍♂️ man in lotus position: medium skin tone
🧖‍♂️ man in steamy room
🧖🏿‍♂️ man in steamy room: dark skin tone
🧖🏻‍♂️ man in steamy room: light skin tone
🧖🏾‍♂️ man in steamy room: mediumdark skin tone
🧖🏼‍♂️ man in steamy room: mediumlight skin tone
🧖🏽‍♂️ man in steamy room: medium skin tone
🕴️ man in suit levitating
🕴🏿 man in suit levitating: dark skin tone
🕴🏻 man in suit levitating: light skin tone
🕴🏾 man in suit levitating: mediumdark skin tone
🕴🏼 man in suit levitating: mediumlight skin tone
🕴🏽 man in suit levitating: medium skin tone
🤵 man in tuxedo
🤵🏿 man in tuxedo: dark skin tone
🤵🏻 man in tuxedo: light skin tone
🤵🏾 man in tuxedo: mediumdark skin tone
🤵🏼 man in tuxedo: mediumlight skin tone
🤵🏽 man in tuxedo: medium skin tone
👨‍⚖️ man judge
👨🏿‍⚖ man judge: dark skin tone
👨🏻‍⚖ man judge: light skin tone
👨🏾‍⚖ man judge: mediumdark skin tone
👨🏼‍⚖ man judge: mediumlight skin tone
👨🏽‍⚖ man judge: medium skin tone
🤹‍♂️ man juggling
🤹🏿‍♂️ man juggling: dark skin tone
🤹🏻‍♂️ man juggling: light skin tone
🤹🏾‍♂️ man juggling: mediumdark skin tone
🤹🏼‍♂️ man juggling: mediumlight skin tone
🤹🏽‍♂️ man juggling: medium skin tone
🧎‍♂️ man kneeling
🧎🏿‍♂️ man kneeling: dark skin tone
🧎🏻‍♂️ man kneeling: light skin tone
🧎🏾‍♂️ man kneeling: mediumdark skin tone
🧎🏼‍♂️ man kneeling: mediumlight skin tone
🧎🏽‍♂️ man kneeling: medium skin tone
🏋️‍♂️ man lifting weights
🏋🏿‍♂️ man lifting weights: dark skin tone
🏋🏻‍♂️ man lifting weights: light skin tone
🏋🏾‍♂️ man lifting weights: mediumdark skin tone
🏋🏼‍♂️ man lifting weights: mediumlight skin tone
🏋🏽‍♂️ man lifting weights: medium skin tone
👨🏻 man: light skin tone
👨‍🔧 man mechanic
👨🏿‍🔧 man mechanic: dark skin tone
👨🏻‍🔧 man mechanic: light skin tone
👨🏾‍🔧 man mechanic: mediumdark skin tone
👨🏼‍🔧 man mechanic: mediumlight skin tone
👨🏽‍🔧 man mechanic: medium skin tone
👨🏾 man: mediumdark skin tone
👨🏼 man: mediumlight skin tone
👨🏽 man: medium skin tone
🚵‍♂️ man mountain biking
🚵🏿‍♂️ man mountain biking: dark skin tone
🚵🏻‍♂️ man mountain biking: light skin tone
🚵🏾‍♂️ man mountain biking: mediumdark skin tone
🚵🏼‍♂️ man mountain biking: mediumlight skin tone
🚵🏽‍♂️ man mountain biking: medium skin tone
👨‍💼 man office worker
👨🏿‍💼 man office worker: dark skin tone
👨🏻‍💼 man office worker: light skin tone
👨🏾‍💼 man office worker: mediumdark skin tone
👨🏼‍💼 man office worker: mediumlight skin tone
👨🏽‍💼 man office worker: medium skin tone
👨‍🦽 man person in manual wheelchair
👨🏿‍🦽 man person in manual wheelchair: dark skin tone
👨🏻‍🦽 man person in manual wheelchair: light skin tone
👨🏾‍🦽 man person in manual wheelchair: mediumdark skin tone
👨🏼‍🦽 man person in manual wheelchair: mediumlight skin tone
👨🏽‍🦽 man person in manual wheelchair: medium skin tone
👨‍🦼 man person in motorized wheelchair
👨🏿‍🦼 man person in motorized wheelchair: dark skin tone
👨🏻‍🦼 man person in motorized wheelchair: light skin tone
👨🏾‍🦼 man person in motorized wheelchair: mediumdark skin tone
👨🏼‍🦼 man person in motorized wheelchair: mediumlight skin tone
👨🏽‍🦼 man person in motorized wheelchair: medium skin tone
👨‍🦯 man person with probing cane
👨🏿‍🦯 man person with probing cane: dark skin tone
👨🏻‍🦯 man person with probing cane: light skin tone
👨🏾‍🦯 man person with probing cane: mediumdark skin tone
👨🏼‍🦯 man person with probing cane: mediumlight skin tone
👨🏽‍🦯 man person with probing cane: medium skin tone
👨‍✈️ man pilot
👨🏿‍✈ man pilot: dark skin tone
👨🏻‍✈ man pilot: light skin tone
👨🏾‍✈ man pilot: mediumdark skin tone
👨🏼‍✈ man pilot: mediumlight skin tone
👨🏽‍✈ man pilot: medium skin tone
🤾‍♂️ man playing handball
🤾🏿‍♂️ man playing handball: dark skin tone
🤾🏻‍♂️ man playing handball: light skin tone
🤾🏾‍♂️ man playing handball: mediumdark skin tone
🤾🏼‍♂️ man playing handball: mediumlight skin tone
🤾🏽‍♂️ man playing handball: medium skin tone
🤽‍♂️ man playing water polo
🤽🏿‍♂️ man playing water polo: dark skin tone
🤽🏻‍♂️ man playing water polo: light skin tone
🤽🏾‍♂️ man playing water polo: mediumdark skin tone
🤽🏼‍♂️ man playing water polo: mediumlight skin tone
🤽🏽‍♂️ man playing water polo: medium skin tone
🙎‍♂️ man pouting
🙎🏿‍♂️ man pouting: dark skin tone
🙎🏻‍♂️ man pouting: light skin tone
🙎🏾‍♂️ man pouting: mediumdark skin tone
🙎🏼‍♂️ man pouting: mediumlight skin tone
🙎🏽‍♂️ man pouting: medium skin tone
🙋‍♂️ man raising hand
🙋🏿‍♂️ man raising hand: dark skin tone
🙋🏻‍♂️ man raising hand: light skin tone
🙋🏾‍♂️ man raising hand: mediumdark skin tone
🙋🏼‍♂️ man raising hand: mediumlight skin tone
🙋🏽‍♂️ man raising hand: medium skin tone
👨‍🦰 man: red hair
👨🏿‍🦰 man: red hair: dark skin tone
👨🏻‍🦰 man: red hair: light skin tone
👨🏾‍🦰 man: red hair: mediumdark skin tone
👨🏼‍🦰 man: red hair: mediumlight skin tone
👨🏽‍🦰 man: red hair: medium skin tone
🚣‍♂️ man rowing boat
🚣🏿‍♂️ man rowing boat: dark skin tone
🚣🏻‍♂️ man rowing boat: light skin tone
🚣🏾‍♂️ man rowing boat: mediumdark skin tone
🚣🏼‍♂️ man rowing boat: mediumlight skin tone
🚣🏽‍♂️ man rowing boat: medium skin tone
🏃‍♂️ man running
🏃🏿‍♂️ man running: dark skin tone
🏃🏻‍♂️ man running: light skin tone
🏃🏾‍♂️ man running: mediumdark skin tone
🏃🏼‍♂️ man running: mediumlight skin tone
🏃🏽‍♂️ man running: medium skin tone
👨‍🔬 man scientist
👨🏿‍🔬 man scientist: dark skin tone
👨🏻‍🔬 man scientist: light skin tone
👨🏾‍🔬 man scientist: mediumdark skin tone
👨🏼‍🔬 man scientist: mediumlight skin tone
👨🏽‍🔬 man scientist: medium skin tone
🤷‍♂️ man shrugging
🤷🏿‍♂️ man shrugging: dark skin tone
🤷🏻‍♂️ man shrugging: light skin tone
🤷🏾‍♂️ man shrugging: mediumdark skin tone
🤷🏼‍♂️ man shrugging: mediumlight skin tone
🤷🏽‍♂️ man shrugging: medium skin tone
👨‍🎤 man singer
👨🏿‍🎤 man singer: dark skin tone
👨🏻‍🎤 man singer: light skin tone
👨🏾‍🎤 man singer: mediumdark skin tone
👨🏼‍🎤 man singer: mediumlight skin tone
👨🏽‍🎤 man singer: medium skin tone
👞 man’s shoe
🧍‍♂️ man standing
🧍🏿‍♂️ man standing: dark skin tone
🧍🏻‍♂️ man standing: light skin tone
🧍🏾‍♂️ man standing: mediumdark skin tone
🧍🏼‍♂️ man standing: mediumlight skin tone
🧍🏽‍♂️ man standing: medium skin tone
👨‍🎓 man student
👨🏿‍🎓 man student: dark skin tone
👨🏻‍🎓 man student: light skin tone
👨🏾‍🎓 man student: mediumdark skin tone
👨🏼‍🎓 man student: mediumlight skin tone
👨🏽‍🎓 man student: medium skin tone
🏄‍♂️ man surfing
🏄🏿‍♂️ man surfing: dark skin tone
🏄🏻‍♂️ man surfing: light skin tone
🏄🏾‍♂️ man surfing: mediumdark skin tone
🏄🏼‍♂️ man surfing: mediumlight skin tone
🏄🏽‍♂️ man surfing: medium skin tone
🏊‍♂️ man swimming
🏊🏿‍♂️ man swimming: dark skin tone
🏊🏻‍♂️ man swimming: light skin tone
🏊🏾‍♂️ man swimming: mediumdark skin tone
🏊🏼‍♂️ man swimming: mediumlight skin tone
🏊🏽‍♂️ man swimming: medium skin tone
👨‍🏫 man teacher
👨🏿‍🏫 man teacher: dark skin tone
👨🏻‍🏫 man teacher: light skin tone
👨🏾‍🏫 man teacher: mediumdark skin tone
👨🏼‍🏫 man teacher: mediumlight skin tone
👨🏽‍🏫 man teacher: medium skin tone
👨‍💻 man technologist
👨🏿‍💻 man technologist: dark skin tone
👨🏻‍💻 man technologist: light skin tone
👨🏾‍💻 man technologist: mediumdark skin tone
👨🏼‍💻 man technologist: mediumlight skin tone
👨🏽‍💻 man technologist: medium skin tone
🕰️ mantelpiece clock
💁‍♂️ man tipping hand
💁🏿‍♂️ man tipping hand: dark skin tone
💁🏻‍♂️ man tipping hand: light skin tone
💁🏾‍♂️ man tipping hand: mediumdark skin tone
💁🏼‍♂️ man tipping hand: mediumlight skin tone
💁🏽‍♂️ man tipping hand: medium skin tone
🦽 manual wheelchair
🚶‍♂️ man walking
🚶🏿‍♂️ man walking: dark skin tone
🚶🏻‍♂️ man walking: light skin tone
🚶🏾‍♂️ man walking: mediumdark skin tone
🚶🏼‍♂️ man walking: mediumlight skin tone
🚶🏽‍♂️ man walking: medium skin tone
👳‍♂️ man wearing turban
👳🏿‍♂️ man wearing turban: dark skin tone
👳🏻‍♂️ man wearing turban: light skin tone
👳🏾‍♂️ man wearing turban: mediumdark skin tone
👳🏼‍♂️ man wearing turban: mediumlight skin tone
👳🏽‍♂️ man wearing turban: medium skin tone
👨‍🦳 man: white hair
👨🏿‍🦳 man: white hair: dark skin tone
👨🏻‍🦳 man: white hair: light skin tone
👨🏾‍🦳 man: white hair: mediumdark skin tone
👨🏼‍🦳 man: white hair: mediumlight skin tone
👨🏽‍🦳 man: white hair: medium skin tone
👲 man with skullcap
👲🏿 man with skullcap: dark skin tone
👲🏻 man with skullcap: light skin tone
👲🏾 man with skullcap: mediumdark skin tone
👲🏼 man with skullcap: mediumlight skin tone
👲🏽 man with skullcap: medium skin tone
🍁 maple leaf
🗾 map of Japan
🥋 martial arts uniform
🧉 mate
🍖 meat on bone
🧑‍🔧 mechanic
🦾 mechanical arm
🦿 mechanical leg
🧑🏿‍🔧 mechanic: dark skin tone
🧑🏻‍🔧 mechanic: light skin tone
🧑🏾‍🔧 mechanic: mediumdark skin tone
🧑🏼‍🔧 mechanic: mediumlight skin tone
🧑🏽‍🔧 mechanic: medium skin tone
⚕️ medical symbol
📣 megaphone
🍈 melon
📝 memo
👬 men holding hands
🕎 menorah
🚹 men’s room
🧜‍♂️ merman
🧜🏿‍♂️ merman: dark skin tone
🧜🏻‍♂️ merman: light skin tone
🧜🏾‍♂️ merman: mediumdark skin tone
🧜🏼‍♂️ merman: mediumlight skin tone
🧜🏽‍♂️ merman: medium skin tone
🧜 merperson
🧜🏿 merperson: dark skin tone
🧜🏻 merperson: light skin tone
🧜🏾 merperson: mediumdark skin tone
🧜🏼 merperson: mediumlight skin tone
🧜🏽 merperson: medium skin tone
🧜‍♀️ merwoman
🧜🏿‍♀️ merwoman: dark skin tone
🧜🏻‍♀️ merwoman: light skin tone
🧜🏾‍♀️ merwoman: mediumdark skin tone
🧜🏼‍♀️ merwoman: mediumlight skin tone
🧜🏽‍♀️ merwoman: medium skin tone
🚇 metro
🦠 microbe
🎤 microphone
🔬 microscope
🖕 middle finger
🖕🏿 middle finger: dark skin tone
🖕🏻 middle finger: light skin tone
🖕🏾 middle finger: mediumdark skin tone
🖕🏼 middle finger: mediumlight skin tone
🖕🏽 middle finger: medium skin tone
🎖️ military medal
🌌 milky way
🚐 minibus
➖ minus sign
🗿 moai
📱 mobile phone
📴 mobile phone off
📲 mobile phone with arrow
💰 money bag
🤑 money-mouth face
💸 money with wings
🐒 monkey
🐵 monkey face
🚝 monorail
🥮 moon cake
🎑 moon viewing ceremony
🕌 mosque
🦟 mosquito
🛥️ motor boat
🏍️ motorcycle
🦼 motorized wheelchair
🛵 motor scooter
🛣️ motorway
⛰️ mountain
🚠 mountain cableway
🚞 mountain railway
🗻 mount fuji
🐁 mouse
🐭 mouse face
👄 mouth
🎥 movie camera
🤶 Mrs. Claus
🤶🏿 Mrs. Claus: dark skin tone
🤶🏻 Mrs. Claus: light skin tone
🤶🏾 Mrs. Claus: mediumdark skin tone
🤶🏼 Mrs. Claus: mediumlight skin tone
🤶🏽 Mrs. Claus: medium skin tone
✖️ multiplication sign
🍄 mushroom
🎹 musical keyboard
🎵 musical note
🎶 musical notes
🎼 musical score
🔇 muted speaker
💅 nail polish
💅🏿 nail polish: dark skin tone
💅🏻 nail polish: light skin tone
💅🏾 nail polish: mediumdark skin tone
💅🏼 nail polish: mediumlight skin tone
💅🏽 nail polish: medium skin tone
📛 name badge
🏞️ national park
🤢 nauseated face
🧿 nazar amulet
👔 necktie
🤓 nerd face
😐 neutral face
🆕 NEW button
🌑 new moon
🌚 new moon face
📰 newspaper
⏭️ next track button
🆖 NG button
🌃 night with stars
🕘 nine o’clock
🕤 nine-thirty
🚳 no bicycles
⛔ no entry
🚯 no littering
📵 no mobile phones
🚱 non-potable water
🔞 no one under eighteen
🚷 no pedestrians
👃 nose
👃🏿 nose: dark skin tone
👃🏻 nose: light skin tone
👃🏾 nose: mediumdark skin tone
👃🏼 nose: mediumlight skin tone
👃🏽 nose: medium skin tone
🚭 no smoking
📓 notebook
📔 notebook with decorative cover
🔩 nut and bolt
🅾️ O button (blood type)
🐙 octopus
🍢 oden
🏢 office building
🧑‍💼 office worker
🧑🏿‍💼 office worker: dark skin tone
🧑🏻‍💼 office worker: light skin tone
🧑🏾‍💼 office worker: mediumdark skin tone
🧑🏼‍💼 office worker: mediumlight skin tone
🧑🏽‍💼 office worker: medium skin tone
👹 ogre
🛢️ oil drum
🆗 OK button
👌 OK hand
👌🏿 OK hand: dark skin tone
👌🏻 OK hand: light skin tone
👌🏾 OK hand: mediumdark skin tone
👌🏼 OK hand: mediumlight skin tone
👌🏽 OK hand: medium skin tone
🧓 older person
🧓🏿 older person: dark skin tone
🧓🏻 older person: light skin tone
🧓🏾 older person: mediumdark skin tone
🧓🏼 older person: mediumlight skin tone
🧓🏽 older person: medium skin tone
🗝️ old key
👴 old man
👴🏿 old man: dark skin tone
👴🏻 old man: light skin tone
👴🏾 old man: mediumdark skin tone
👴🏼 old man: mediumlight skin tone
👴🏽 old man: medium skin tone
👵 old woman
👵🏿 old woman: dark skin tone
👵🏻 old woman: light skin tone
👵🏾 old woman: mediumdark skin tone
👵🏼 old woman: mediumlight skin tone
👵🏽 old woman: medium skin tone
🕉️ om
🔛 ON! arrow
🚘 oncoming automobile
🚍 oncoming bus
👊 oncoming fist
👊🏿 oncoming fist: dark skin tone
👊🏻 oncoming fist: light skin tone
👊🏾 oncoming fist: mediumdark skin tone
👊🏼 oncoming fist: mediumlight skin tone
👊🏽 oncoming fist: medium skin tone
🚔 oncoming police car
🚖 oncoming taxi
🕐 one o’clock
🩱 one-piece swimsuit
🕜 one-thirty
🧅 onion
📖 open book
📂 open file folder
👐 open hands
👐🏿 open hands: dark skin tone
👐🏻 open hands: light skin tone
👐🏾 open hands: mediumdark skin tone
👐🏼 open hands: mediumlight skin tone
👐🏽 open hands: medium skin tone
📭 open mailbox with lowered flag
📬 open mailbox with raised flag
⛎ Ophiuchus
💿 optical disk
📙 orange book
🟠 orange circle
🧡 orange heart
🟧 orange square
🦧 orangutan
☦️ orthodox cross
🦦 otter
📤 outbox tray
🦉 owl
🐂 ox
🦪 oyster
📦 package
📄 page facing up
📟 pager
📃 page with curl
🖌️ paintbrush
🤲 palms up together
🤲🏿 palms up together: dark skin tone
🤲🏻 palms up together: light skin tone
🤲🏾 palms up together: mediumdark skin tone
🤲🏼 palms up together: mediumlight skin tone
🤲🏽 palms up together: medium skin tone
🌴 palm tree
🥞 pancakes
🐼 panda
📎 paperclip
🪂 parachute
🦜 parrot
〽️ part alternation mark
🥳 partying face
🎉 party popper
🛳️ passenger ship
🛂 passport control
⏸️ pause button
🐾 paw prints
🅿️ P button
☮️ peace symbol
🍑 peach
🦚 peacock
🥜 peanuts
🍐 pear
🖊️ pen
✏️ pencil
🐧 penguin
😔 pensive face
🧑‍🤝‍🧑 people holding hands
👯 people with bunny ears
👯‍♂️ people with bunny ears
🤼 people wrestling
🤼‍♂️ people wrestling
🎭 performing arts
😣 persevering face
🧑 person
🧑‍🦲 person: bald
🧑🏿‍🦲 person: bald: dark skin tone
🧑🏻‍🦲 person: bald: light skin tone
🧑🏾‍🦲 person: bald: mediumdark skin tone
🧑🏼‍🦲 person: bald: mediumlight skin tone
🧑🏽‍🦲 person: bald: medium skin tone
🚴 person biking
🚴🏿 person biking: dark skin tone
🚴🏻 person biking: light skin tone
🚴🏾 person biking: mediumdark skin tone
🚴🏼 person biking: mediumlight skin tone
🚴🏽 person biking: medium skin tone
👱 person: blond hair
👱🏿 person: blond hair: dark skin tone
👱🏻 person: blond hair: light skin tone
👱🏾 person: blond hair: mediumdark skin tone
👱🏼 person: blond hair: mediumlight skin tone
👱🏽 person: blond hair: medium skin tone
⛹️ person bouncing ball
⛹🏿 person bouncing ball: dark skin tone
⛹🏻 person bouncing ball: light skin tone
⛹🏾 person bouncing ball: mediumdark skin tone
⛹🏼 person bouncing ball: mediumlight skin tone
⛹🏽 person bouncing ball: medium skin tone
🙇 person bowing
🙇🏿 person bowing: dark skin tone
🙇🏻 person bowing: light skin tone
🙇🏾 person bowing: mediumdark skin tone
🙇🏼 person bowing: mediumlight skin tone
🙇🏽 person bowing: medium skin tone
🤸 person cartwheeling
🤸🏿 person cartwheeling: dark skin tone
🤸🏻 person cartwheeling: light skin tone
🤸🏾 person cartwheeling: mediumdark skin tone
🤸🏼 person cartwheeling: mediumlight skin tone
🤸🏽 person cartwheeling: medium skin tone
🧗 person climbing
🧗🏿 person climbing: dark skin tone
🧗🏻 person climbing: light skin tone
🧗🏾 person climbing: mediumdark skin tone
🧗🏼 person climbing: mediumlight skin tone
🧗🏽 person climbing: medium skin tone
🧑‍🦱 person: curly hair
🧑🏿‍🦱 person: curly hair: dark skin tone
🧑🏻‍🦱 person: curly hair: light skin tone
🧑🏾‍🦱 person: curly hair: mediumdark skin tone
🧑🏼‍🦱 person: curly hair: mediumlight skin tone
🧑🏽‍🦱 person: curly hair: medium skin tone
🧑🏿 person: dark skin tone
🤦 person facepalming
🤦🏿 person facepalming: dark skin tone
🤦🏻 person facepalming: light skin tone
🤦🏾 person facepalming: mediumdark skin tone
🤦🏼 person facepalming: mediumlight skin tone
🤦🏽 person facepalming: medium skin tone
🤺 person fencing
🙍 person frowning
🙍🏿 person frowning: dark skin tone
🙍🏻 person frowning: light skin tone
🙍🏾 person frowning: mediumdark skin tone
🙍🏼 person frowning: mediumlight skin tone
🙍🏽 person frowning: medium skin tone
🙅 person gesturing NO
🙅🏿 person gesturing NO: dark skin tone
🙅🏻 person gesturing NO: light skin tone
🙅🏾 person gesturing NO: mediumdark skin tone
🙅🏼 person gesturing NO: mediumlight skin tone
🙅🏽 person gesturing NO: medium skin tone
🙆 person gesturing OK
🙆🏿 person gesturing OK: dark skin tone
🙆🏻 person gesturing OK: light skin tone
🙆🏾 person gesturing OK: mediumdark skin tone
🙆🏼 person gesturing OK: mediumlight skin tone
🙆🏽 person gesturing OK: medium skin tone
💇 person getting haircut
💇🏿 person getting haircut: dark skin tone
💇🏻 person getting haircut: light skin tone
💇🏾 person getting haircut: mediumdark skin tone
💇🏼 person getting haircut: mediumlight skin tone
💇🏽 person getting haircut: medium skin tone
💆 person getting massage
💆🏿 person getting massage: dark skin tone
💆🏻 person getting massage: light skin tone
💆🏾 person getting massage: mediumdark skin tone
💆🏼 person getting massage: mediumlight skin tone
💆🏽 person getting massage: medium skin tone
🏌️ person golfing
🏌🏿 person golfing: dark skin tone
🏌🏻 person golfing: light skin tone
🏌🏾 person golfing: mediumdark skin tone
🏌🏼 person golfing: mediumlight skin tone
🏌🏽 person golfing: medium skin tone
🛌 person in bed
🛌🏿 person in bed: dark skin tone
🛌🏻 person in bed: light skin tone
🛌🏾 person in bed: mediumdark skin tone
🛌🏼 person in bed: mediumlight skin tone
🛌🏽 person in bed: medium skin tone
🧘 person in lotus position
🧘🏿 person in lotus position: dark skin tone
🧘🏻 person in lotus position: light skin tone
🧘🏾 person in lotus position: mediumdark skin tone
🧘🏼 person in lotus position: mediumlight skin tone
🧘🏽 person in lotus position: medium skin tone
🧑‍🦽 person in manual wheelchair
🧑🏿‍🦽 person in manual wheelchair: dark skin tone
🧑🏻‍🦽 person in manual wheelchair: light skin tone
🧑🏾‍🦽 person in manual wheelchair: mediumdark skin tone
🧑🏼‍🦽 person in manual wheelchair: mediumlight skin tone
🧑🏽‍🦽 person in manual wheelchair: medium skin tone
🧑‍🦼 person in motorized wheelchair
🧑🏿‍🦼 person in motorized wheelchair: dark skin tone
🧑🏻‍🦼 person in motorized wheelchair: light skin tone
🧑🏾‍🦼 person in motorized wheelchair: mediumdark skin tone
🧑🏼‍🦼 person in motorized wheelchair: mediumlight skin tone
🧑🏽‍🦼 person in motorized wheelchair: medium skin tone
🧖 person in steamy room
🧖🏿 person in steamy room: dark skin tone
🧖🏻 person in steamy room: light skin tone
🧖🏾 person in steamy room: mediumdark skin tone
🧖🏼 person in steamy room: mediumlight skin tone
🧖🏽 person in steamy room: medium skin tone
🤹 person juggling
🤹🏿 person juggling: dark skin tone
🤹🏻 person juggling: light skin tone
🤹🏾 person juggling: mediumdark skin tone
🤹🏼 person juggling: mediumlight skin tone
🤹🏽 person juggling: medium skin tone
🧎 person kneeling
🧎🏿 person kneeling: dark skin tone
🧎🏻 person kneeling: light skin tone
🧎🏾 person kneeling: mediumdark skin tone
🧎🏼 person kneeling: mediumlight skin tone
🧎🏽 person kneeling: medium skin tone
🏋️ person lifting weights
🏋🏿 person lifting weights: dark skin tone
🏋🏻 person lifting weights: light skin tone
🏋🏾 person lifting weights: mediumdark skin tone
🏋🏼 person lifting weights: mediumlight skin tone
🏋🏽 person lifting weights: medium skin tone
🧑🏻 person: light skin tone
🧑🏾 person: mediumdark skin tone
🧑🏼 person: mediumlight skin tone
🧑🏽 person: medium skin tone
🚵 person mountain biking
🚵🏿 person mountain biking: dark skin tone
🚵🏻 person mountain biking: light skin tone
🚵🏾 person mountain biking: mediumdark skin tone
🚵🏼 person mountain biking: mediumlight skin tone
🚵🏽 person mountain biking: medium skin tone
🤾 person playing handball
🤾🏿 person playing handball: dark skin tone
🤾🏻 person playing handball: light skin tone
🤾🏾 person playing handball: mediumdark skin tone
🤾🏼 person playing handball: mediumlight skin tone
🤾🏽 person playing handball: medium skin tone
🤽 person playing water polo
🤽🏿 person playing water polo: dark skin tone
🤽🏻 person playing water polo: light skin tone
🤽🏾 person playing water polo: mediumdark skin tone
🤽🏼 person playing water polo: mediumlight skin tone
🤽🏽 person playing water polo: medium skin tone
🙎 person pouting
🙎🏿 person pouting: dark skin tone
🙎🏻 person pouting: light skin tone
🙎🏾 person pouting: mediumdark skin tone
🙎🏼 person pouting: mediumlight skin tone
🙎🏽 person pouting: medium skin tone
🙋 person raising hand
🙋🏿 person raising hand: dark skin tone
🙋🏻 person raising hand: light skin tone
🙋🏾 person raising hand: mediumdark skin tone
🙋🏼 person raising hand: mediumlight skin tone
🙋🏽 person raising hand: medium skin tone
🧑‍🦰 person: red hair
🧑🏿‍🦰 person: red hair: dark skin tone
🧑🏻‍🦰 person: red hair: light skin tone
🧑🏾‍🦰 person: red hair: mediumdark skin tone
🧑🏼‍🦰 person: red hair: mediumlight skin tone
🧑🏽‍🦰 person: red hair: medium skin tone
🚣 person rowing boat
🚣🏿 person rowing boat: dark skin tone
🚣🏻 person rowing boat: light skin tone
🚣🏾 person rowing boat: mediumdark skin tone
🚣🏼 person rowing boat: mediumlight skin tone
🚣🏽 person rowing boat: medium skin tone
🏃 person running
🏃🏿 person running: dark skin tone
🏃🏻 person running: light skin tone
🏃🏾 person running: mediumdark skin tone
🏃🏼 person running: mediumlight skin tone
🏃🏽 person running: medium skin tone
🤷 person shrugging
🤷🏿 person shrugging: dark skin tone
🤷🏻 person shrugging: light skin tone
🤷🏾 person shrugging: mediumdark skin tone
🤷🏼 person shrugging: mediumlight skin tone
🤷🏽 person shrugging: medium skin tone
🧍 person standing
🧍🏿 person standing: dark skin tone
🧍🏻 person standing: light skin tone
🧍🏾 person standing: mediumdark skin tone
🧍🏼 person standing: mediumlight skin tone
🧍🏽 person standing: medium skin tone
🏄 person surfing
🏄🏿 person surfing: dark skin tone
🏄🏻 person surfing: light skin tone
🏄🏾 person surfing: mediumdark skin tone
🏄🏼 person surfing: mediumlight skin tone
🏄🏽 person surfing: medium skin tone
🏊 person swimming
🏊🏿 person swimming: dark skin tone
🏊🏻 person swimming: light skin tone
🏊🏾 person swimming: mediumdark skin tone
🏊🏼 person swimming: mediumlight skin tone
🏊🏽 person swimming: medium skin tone
🛀 person taking bath
🛀🏿 person taking bath: dark skin tone
🛀🏻 person taking bath: light skin tone
🛀🏾 person taking bath: mediumdark skin tone
🛀🏼 person taking bath: mediumlight skin tone
🛀🏽 person taking bath: medium skin tone
💁 person tipping hand
💁🏿 person tipping hand: dark skin tone
💁🏻 person tipping hand: light skin tone
💁🏾 person tipping hand: mediumdark skin tone
💁🏼 person tipping hand: mediumlight skin tone
💁🏽 person tipping hand: medium skin tone
🚶 person walking
🚶🏿 person walking: dark skin tone
🚶🏻 person walking: light skin tone
🚶🏾 person walking: mediumdark skin tone
🚶🏼 person walking: mediumlight skin tone
🚶🏽 person walking: medium skin tone
👳 person wearing turban
👳🏿 person wearing turban: dark skin tone
👳🏻 person wearing turban: light skin tone
👳🏾 person wearing turban: mediumdark skin tone
👳🏼 person wearing turban: mediumlight skin tone
👳🏽 person wearing turban: medium skin tone
🧑‍🦳 person: white hair
🧑🏿‍🦳 person: white hair: dark skin tone
🧑🏻‍🦳 person: white hair: light skin tone
🧑🏾‍🦳 person: white hair: mediumdark skin tone
🧑🏼‍🦳 person: white hair: mediumlight skin tone
🧑🏽‍🦳 person: white hair: medium skin tone
🧑‍🦯 person with probing cane
🧑🏿‍🦯 person with probing cane: dark skin tone
🧑🏻‍🦯 person with probing cane: light skin tone
🧑🏾‍🦯 person with probing cane: mediumdark skin tone
🧑🏼‍🦯 person with probing cane: mediumlight skin tone
🧑🏽‍🦯 person with probing cane: medium skin tone
🧫 petri dish
⛏️ pick
🥧 pie
🐖 pig
🐷 pig face
🐽 pig nose
💩 pile of poo
💊 pill
🧑‍✈️ pilot
🧑🏿‍✈ pilot: dark skin tone
🧑🏻‍✈ pilot: light skin tone
🧑🏾‍✈ pilot: mediumdark skin tone
🧑🏼‍✈ pilot: mediumlight skin tone
🧑🏽‍✈ pilot: medium skin tone
🤏 pinching hand
🤏🏿 pinching hand: dark skin tone
🤏🏻 pinching hand: light skin tone
🤏🏾 pinching hand: mediumdark skin tone
🤏🏼 pinching hand: mediumlight skin tone
🤏🏽 pinching hand: medium skin tone
🍍 pineapple
🎍 pine decoration
🏓 ping pong
🏴‍☠️ pirate flag
♓ Pisces
🔫 pistol
🍕 pizza
🛐 place of worship
▶️ play button
⏯️ play or pause button
🥺 pleading face
➕ plus sign
🚓 police car
🚨 police car light
👮 police officer
👮‍♂️ police officer
👮🏿 police officer: dark skin tone
👮🏿‍♂️ police officer: dark skin tone
👮🏻 police officer: light skin tone
👮🏻‍♂️ police officer: light skin tone
👮🏾 police officer: mediumdark skin tone
👮🏾‍♂️ police officer: mediumdark skin tone
👮🏼 police officer: mediumlight skin tone
👮🏼‍♂️ police officer: mediumlight skin tone
👮🏽 police officer: medium skin tone
👮🏽‍♂️ police officer: medium skin tone
🐩 poodle
🎱 pool 8 ball
🍿 popcorn
📯 postal horn
📮 postbox
🏤 post office
🚰 potable water
🥔 potato
🍲 pot of food
🍗 poultry leg
💷 pound banknote
😾 pouting cat
😡 pouting face
📿 prayer beads
🤰 pregnant woman
🤰🏿 pregnant woman: dark skin tone
🤰🏻 pregnant woman: light skin tone
🤰🏾 pregnant woman: mediumdark skin tone
🤰🏼 pregnant woman: mediumlight skin tone
🤰🏽 pregnant woman: medium skin tone
🥨 pretzel
🤴 prince
🤴🏿 prince: dark skin tone
🤴🏻 prince: light skin tone
🤴🏾 prince: mediumdark skin tone
🤴🏼 prince: mediumlight skin tone
🤴🏽 prince: medium skin tone
👸 princess
👸🏿 princess: dark skin tone
👸🏻 princess: light skin tone
👸🏾 princess: mediumdark skin tone
👸🏼 princess: mediumlight skin tone
👸🏽 princess: medium skin tone
🖨️ printer
🦯 probing cane
🚫 prohibited
🟣 purple circle
💜 purple heart
🟪 purple square
👛 purse
📌 pushpin
🧩 puzzle piece
❓ question mark
🐇 rabbit
🐰 rabbit face
🦝 raccoon
🏎️ racing car
📻 radio
☢️ radioactive
🔘 radio button
🚃 railway car
🛤️ railway track
🌈 rainbow
🏳️‍🌈 rainbow flag
🤚 raised back of hand
🤚🏿 raised back of hand: dark skin tone
🤚🏻 raised back of hand: light skin tone
🤚🏾 raised back of hand: mediumdark skin tone
🤚🏼 raised back of hand: mediumlight skin tone
🤚🏽 raised back of hand: medium skin tone
✊ raised fist
✊🏿 raised fist: dark skin tone
✊🏻 raised fist: light skin tone
✊🏾 raised fist: mediumdark skin tone
✊🏼 raised fist: mediumlight skin tone
✊🏽 raised fist: medium skin tone
✋ raised hand
✋🏿 raised hand: dark skin tone
✋🏻 raised hand: light skin tone
✋🏾 raised hand: mediumdark skin tone
✋🏼 raised hand: mediumlight skin tone
✋🏽 raised hand: medium skin tone
🙌 raising hands
🙌🏿 raising hands: dark skin tone
🙌🏻 raising hands: light skin tone
🙌🏾 raising hands: mediumdark skin tone
🙌🏼 raising hands: mediumlight skin tone
🙌🏽 raising hands: medium skin tone
🐏 ram
🐀 rat
🪒 razor
🧾 receipt
⏺️ record button
♻️ recycling symbol
🍎 red apple
🔴 red circle
🧧 red envelope
❤️ red heart
🏮 red paper lantern
🟥 red square
🔻 red triangle pointed down
🔺 red triangle pointed up
®️ registered
😌 relieved face
🎗️ reminder ribbon
🔁 repeat button
🔂 repeat single button
⛑️ rescue worker’s helmet
🚻 restroom
◀️ reverse button
💞 revolving hearts
🦏 rhinoceros
🎀 ribbon
🍙 rice ball
🍘 rice cracker
🗯️ right anger bubble
➡️ right arrow
⤵️ right arrow curving down
↩️ right arrow curving left
⤴️ right arrow curving up
🤜 right-facing fist
🤜🏿 right-facing fist: dark skin tone
🤜🏻 right-facing fist: light skin tone
🤜🏾 right-facing fist: mediumdark skin tone
🤜🏼 right-facing fist: mediumlight skin tone
🤜🏽 right-facing fist: medium skin tone
💍 ring
🪐 ringed planet
🍠 roasted sweet potato
🤖 robot
🚀 rocket
🗞️ rolled-up newspaper
🎢 roller coaster
🤣 rolling on the floor laughing
🧻 roll of paper
🐓 rooster
🌹 rose
🏵️ rosette
📍 round pushpin
🏉 rugby football
🎽 running shirt
👟 running shoe
😥 sad but relieved face
🧷 safety pin
🦺 safety vest
♐ Sagittarius
⛵ sailboat
🍶 sake
🧂 salt
🥪 sandwich
🎅 Santa Claus
🎅🏿 Santa Claus: dark skin tone
🎅🏻 Santa Claus: light skin tone
🎅🏾 Santa Claus: mediumdark skin tone
🎅🏼 Santa Claus: mediumlight skin tone
🎅🏽 Santa Claus: medium skin tone
🥻 sari
🛰️ satellite
📡 satellite antenna
🦕 sauropod
🎷 saxophone
🧣 scarf
🏫 school
🧑‍🔬 scientist
🧑🏿‍🔬 scientist: dark skin tone
🧑🏻‍🔬 scientist: light skin tone
🧑🏾‍🔬 scientist: mediumdark skin tone
🧑🏼‍🔬 scientist: mediumlight skin tone
🧑🏽‍🔬 scientist: medium skin tone
✂️ scissors
♏ Scorpio
🦂 scorpion
📜 scroll
💺 seat
🌱 seedling
🙈 see-no-evil monkey
🤳 selfie
🤳🏿 selfie: dark skin tone
🤳🏻 selfie: light skin tone
🤳🏾 selfie: mediumdark skin tone
🤳🏼 selfie: mediumlight skin tone
🤳🏽 selfie: medium skin tone
🐕‍🦺 service dog
🕖 seven o’clock
🕢 seven-thirty
🥘 shallow pan of food
☘️ shamrock
🦈 shark
🍧 shaved ice
🌾 sheaf of rice
🛡️ shield
⛩️ shinto shrine
🚢 ship
🌠 shooting star
🛍️ shopping bags
🛒 shopping cart
🍰 shortcake
🩳 shorts
🚿 shower
🦐 shrimp
🔀 shuffle tracks button
🤫 shushing face
🤘 sign of the horns
🤘🏿 sign of the horns: dark skin tone
🤘🏻 sign of the horns: light skin tone
🤘🏾 sign of the horns: mediumdark skin tone
🤘🏼 sign of the horns: mediumlight skin tone
🤘🏽 sign of the horns: medium skin tone
🧑‍🎤 singer
🧑🏿‍🎤 singer: dark skin tone
🧑🏻‍🎤 singer: light skin tone
🧑🏾‍🎤 singer: mediumdark skin tone
🧑🏼‍🎤 singer: mediumlight skin tone
🧑🏽‍🎤 singer: medium skin tone
🕕 six o’clock
🕡 six-thirty
🛹 skateboard
⛷️ skier
🎿 skis
💀 skull
☠️ skull and crossbones
🦨 skunk
🛷 sled
😴 sleeping face
😪 sleepy face
🙁 slightly frowning face
🙂 slightly smiling face
🦥 sloth
🎰 slot machine
🛩️ small airplane
🔹 small blue diamond
🔸 small orange diamond
😻 smiling cat with heart-eyes
☺️ smiling face
😇 smiling face with halo
😍 smiling face with heart-eyes
🥰 smiling face with hearts
😈 smiling face with horns
😊 smiling face with smiling eyes
😎 smiling face with sunglasses
😏 smirking face
🐌 snail
🐍 snake
🤧 sneezing face
🏂 snowboarder
🏂🏿 snowboarder: dark skin tone
🏂🏻 snowboarder: light skin tone
🏂🏾 snowboarder: mediumdark skin tone
🏂🏼 snowboarder: mediumlight skin tone
🏂🏽 snowboarder: medium skin tone
🏔️ snow-capped mountain
❄️ snowflake
☃️ snowman
⛄ snowman without snow
🧼 soap
⚽ soccer ball
🧦 socks
🥎 softball
🍦 soft ice cream
🔜 SOON arrow
🆘 SOS button
♠️ spade suit
🍝 spaghetti
❇️ sparkle
🎇 sparkler
✨ sparkles
💖 sparkling heart
🔊 speaker high volume
🔈 speaker low volume
🔉 speaker medium volume
🗣️ speaking head
🙊 speak-no-evil monkey
💬 speech balloon
🚤 speedboat
🕷️ spider
🕸️ spider web
🗓️ spiral calendar
🗒️ spiral notepad
🐚 spiral shell
🧽 sponge
🥄 spoon
🏅 sports medal
🚙 sport utility vehicle
🐳 spouting whale
🦑 squid
😝 squinting face with tongue
🏟️ stadium
⭐ star
☪️ star and crescent
✡️ star of David
🤩 star-struck
🚉 station
🗽 Statue of Liberty
🍜 steaming bowl
🩺 stethoscope
⏹️ stop button
🛑 stop sign
⏱️ stopwatch
📏 straight ruler
🍓 strawberry
🧑‍🎓 student
🧑🏿‍🎓 student: dark skin tone
🧑🏻‍🎓 student: light skin tone
🧑🏾‍🎓 student: mediumdark skin tone
🧑🏼‍🎓 student: mediumlight skin tone
🧑🏽‍🎓 student: medium skin tone
🎙️ studio microphone
🥙 stuffed flatbread
☀️ sun
⛅ sun behind cloud
🌥️ sun behind large cloud
🌦️ sun behind rain cloud
🌤️ sun behind small cloud
🌻 sunflower
🕶️ sunglasses
🌅 sunrise
🌄 sunrise over mountains
🌇 sunset
🌞 sun with face
🦸 superhero
🦸‍♂️ superhero
🦸🏿 superhero: dark skin tone
🦸🏿‍♂️ superhero: dark skin tone
🦸🏻 superhero: light skin tone
🦸🏻‍♂️ superhero: light skin tone
🦸🏾 superhero: mediumdark skin tone
🦸🏾‍♂️ superhero: mediumdark skin tone
🦸🏼 superhero: mediumlight skin tone
🦸🏼‍♂️ superhero: mediumlight skin tone
🦸🏽 superhero: medium skin tone
🦸🏽‍♂️ superhero: medium skin tone
🦹 supervillain
🦹‍♂️ supervillain
🦹🏿 supervillain: dark skin tone
🦹🏿‍♂️ supervillain: dark skin tone
🦹🏻 supervillain: light skin tone
🦹🏻‍♂️ supervillain: light skin tone
🦹🏾 supervillain: mediumdark skin tone
🦹🏾‍♂️ supervillain: mediumdark skin tone
🦹🏼 supervillain: mediumlight skin tone
🦹🏼‍♂️ supervillain: mediumlight skin tone
🦹🏽 supervillain: medium skin tone
🦹🏽‍♂️ supervillain: medium skin tone
🍣 sushi
🚟 suspension railway
🦢 swan
💦 sweat droplets
🕍 synagogue
💉 syringe
🌮 taco
🥡 takeout box
🎋 tanabata tree
🍊 tangerine
♉ Taurus
🚕 taxi
🧑‍🏫 teacher
🧑🏿‍🏫 teacher: dark skin tone
🧑🏻‍🏫 teacher: light skin tone
🧑🏾‍🏫 teacher: mediumdark skin tone
🧑🏼‍🏫 teacher: mediumlight skin tone
🧑🏽‍🏫 teacher: medium skin tone
🍵 teacup without handle
📆 tear-off calendar
🧑‍💻 technologist
🧑🏿‍💻 technologist: dark skin tone
🧑🏻‍💻 technologist: light skin tone
🧑🏾‍💻 technologist: mediumdark skin tone
🧑🏼‍💻 technologist: mediumlight skin tone
🧑🏽‍💻 technologist: medium skin tone
🧸 teddy bear
☎️ telephone
📞 telephone receiver
🔭 telescope
📺 television
🎾 tennis
🕙 ten o’clock
⛺ tent
🕥 ten-thirty
🧪 test tube
🌡️ thermometer
🤔 thinking face
💭 thought balloon
🧵 thread
🕒 three o’clock
🕞 three-thirty
👎 thumbs down
👎🏿 thumbs down: dark skin tone
👎🏻 thumbs down: light skin tone
👎🏾 thumbs down: mediumdark skin tone
👎🏼 thumbs down: mediumlight skin tone
👎🏽 thumbs down: medium skin tone
👍 thumbs up
👍🏿 thumbs up: dark skin tone
👍🏻 thumbs up: light skin tone
👍🏾 thumbs up: mediumdark skin tone
👍🏼 thumbs up: mediumlight skin tone
👍🏽 thumbs up: medium skin tone
🎫 ticket
🐅 tiger
🐯 tiger face
⏲️ timer clock
😫 tired face
🚽 toilet
🗼 Tokyo tower
🍅 tomato
👅 tongue
🧰 toolbox
🦷 tooth
🔝 TOP arrow
🎩 top hat
🌪️ tornado
🖲️ trackball
🚜 tractor
™️ trade mark
🚆 train
🚊 tram
🚋 tram car
🦖 T-Rex
🚩 triangular flag
📐 triangular ruler
🔱 trident emblem
🚎 trolleybus
🏆 trophy
🍹 tropical drink
🐠 tropical fish
🎺 trumpet
👕 t-shirt
🌷 tulip
🥃 tumbler glass
🦃 turkey
🐢 turtle
🕛 twelve o’clock
🕧 twelve-thirty
💕 two hearts
🐫 two-hump camel
🕑 two o’clock
🕝 two-thirty
☂️ umbrella
⛱️ umbrella on ground
☔ umbrella with rain drops
😒 unamused face
🦄 unicorn
🔓 unlocked
⬆️ up arrow
🆙 UP! button
↕️ up-down arrow
↖️ up-left arrow
↗️ up-right arrow
🙃 upside-down face
🔼 upwards button
🧛 vampire
🧛‍♂️ vampire
🧛🏿 vampire: dark skin tone
🧛🏿‍♂️ vampire: dark skin tone
🧛🏻 vampire: light skin tone
🧛🏻‍♂️ vampire: light skin tone
🧛🏾 vampire: mediumdark skin tone
🧛🏾‍♂️ vampire: mediumdark skin tone
🧛🏼 vampire: mediumlight skin tone
🧛🏼‍♂️ vampire: mediumlight skin tone
🧛🏽 vampire: medium skin tone
🧛🏽‍♂️ vampire: medium skin tone
🚦 vertical traffic light
📳 vibration mode
✌️ victory hand
✌🏿 victory hand: dark skin tone
✌🏻 victory hand: light skin tone
✌🏾 victory hand: mediumdark skin tone
✌🏼 victory hand: mediumlight skin tone
✌🏽 victory hand: medium skin tone
📹 video camera
📼 videocassette
🎮 video game
🎻 violin
♍ Virgo
🌋 volcano
🏐 volleyball
🆚 VS button
🖖 vulcan salute
🖖🏿 vulcan salute: dark skin tone
🖖🏻 vulcan salute: light skin tone
🖖🏾 vulcan salute: mediumdark skin tone
🖖🏼 vulcan salute: mediumlight skin tone
🖖🏽 vulcan salute: medium skin tone
🧇 waffle
🌘 waning crescent moon
🌖 waning gibbous moon
⚠️ warning
🗑️ wastebasket
⌚ watch
🐃 water buffalo
🚾 water closet
🍉 watermelon
🌊 water wave
👋 waving hand
👋🏿 waving hand: dark skin tone
👋🏻 waving hand: light skin tone
👋🏾 waving hand: mediumdark skin tone
👋🏼 waving hand: mediumlight skin tone
👋🏽 waving hand: medium skin tone
〰️ wavy dash
🌒 waxing crescent moon
🌔 waxing gibbous moon
🙀 weary cat
😩 weary face
💒 wedding
🐋 whale
♿ wheelchair symbol
☸️ wheel of dharma
⚪ white circle
❕ white exclamation mark
🏳️ white flag
💮 white flower
🤍 white heart
⬜ white large square
◽ white medium-small square
◻️ white medium square
❔ white question mark
▫️ white small square
🔳 white square button
🥀 wilted flower
🎐 wind chime
🌬️ wind face
🍷 wine glass
😉 winking face
😜 winking face with tongue
🐺 wolf
👩 woman
👫 woman and man holding hands
👩‍🎨 woman artist
👩🏿‍🎨 woman artist: dark skin tone
👩🏻‍🎨 woman artist: light skin tone
👩🏾‍🎨 woman artist: mediumdark skin tone
👩🏼‍🎨 woman artist: mediumlight skin tone
👩🏽‍🎨 woman artist: medium skin tone
👩‍🚀 woman astronaut
👩🏿‍🚀 woman astronaut: dark skin tone
👩🏻‍🚀 woman astronaut: light skin tone
👩🏾‍🚀 woman astronaut: mediumdark skin tone
👩🏼‍🚀 woman astronaut: mediumlight skin tone
👩🏽‍🚀 woman astronaut: medium skin tone
👩‍🦲 woman: bald
👩🏿‍🦲 woman: bald: dark skin tone
👩🏻‍🦲 woman: bald: light skin tone
👩🏾‍🦲 woman: bald: mediumdark skin tone
👩🏼‍🦲 woman: bald: mediumlight skin tone
👩🏽‍🦲 woman: bald: medium skin tone
🚴‍♀️ woman biking
🚴🏿‍♀️ woman biking: dark skin tone
🚴🏻‍♀️ woman biking: light skin tone
🚴🏾‍♀️ woman biking: mediumdark skin tone
🚴🏼‍♀️ woman biking: mediumlight skin tone
🚴🏽‍♀️ woman biking: medium skin tone
👱‍♀️ woman: blond hair
👱🏿‍♀️ woman: blond hair: dark skin tone
👱🏻‍♀️ woman: blond hair: light skin tone
👱🏾‍♀️ woman: blond hair: mediumdark skin tone
👱🏼‍♀️ woman: blond hair: mediumlight skin tone
👱🏽‍♀️ woman: blond hair: medium skin tone
⛹️‍♀️ woman bouncing ball
⛹🏿‍♀️ woman bouncing ball: dark skin tone
⛹🏻‍♀️ woman bouncing ball: light skin tone
⛹🏾‍♀️ woman bouncing ball: mediumdark skin tone
⛹🏼‍♀️ woman bouncing ball: mediumlight skin tone
⛹🏽‍♀️ woman bouncing ball: medium skin tone
🙇‍♀️ woman bowing
🙇🏿‍♀️ woman bowing: dark skin tone
🙇🏻‍♀️ woman bowing: light skin tone
🙇🏾‍♀️ woman bowing: mediumdark skin tone
🙇🏼‍♀️ woman bowing: mediumlight skin tone
🙇🏽‍♀️ woman bowing: medium skin tone
🤸‍♀️ woman cartwheeling
🤸🏿‍♀️ woman cartwheeling: dark skin tone
🤸🏻‍♀️ woman cartwheeling: light skin tone
🤸🏾‍♀️ woman cartwheeling: mediumdark skin tone
🤸🏼‍♀️ woman cartwheeling: mediumlight skin tone
🤸🏽‍♀️ woman cartwheeling: medium skin tone
🧗‍♀️ woman climbing
🧗🏿‍♀️ woman climbing: dark skin tone
🧗🏻‍♀️ woman climbing: light skin tone
🧗🏾‍♀️ woman climbing: mediumdark skin tone
🧗🏼‍♀️ woman climbing: mediumlight skin tone
🧗🏽‍♀️ woman climbing: medium skin tone
👩‍🍳 woman cook
👩🏿‍🍳 woman cook: dark skin tone
👩🏻‍🍳 woman cook: light skin tone
👩🏾‍🍳 woman cook: mediumdark skin tone
👩🏼‍🍳 woman cook: mediumlight skin tone
👩🏽‍🍳 woman cook: medium skin tone
👩‍🦱 woman: curly hair
👩🏿‍🦱 woman: curly hair: dark skin tone
👩🏻‍🦱 woman: curly hair: light skin tone
👩🏾‍🦱 woman: curly hair: mediumdark skin tone
👩🏼‍🦱 woman: curly hair: mediumlight skin tone
👩🏽‍🦱 woman: curly hair: medium skin tone
💃 woman dancing
💃🏿 woman dancing: dark skin tone
💃🏻 woman dancing: light skin tone
💃🏾 woman dancing: mediumdark skin tone
💃🏼 woman dancing: mediumlight skin tone
💃🏽 woman dancing: medium skin tone
👩🏿 woman: dark skin tone
🤦‍♀️ woman facepalming
🤦🏿‍♀️ woman facepalming: dark skin tone
🤦🏻‍♀️ woman facepalming: light skin tone
🤦🏾‍♀️ woman facepalming: mediumdark skin tone
🤦🏼‍♀️ woman facepalming: mediumlight skin tone
🤦🏽‍♀️ woman facepalming: medium skin tone
👩‍🏭 woman factory worker
👩🏿‍🏭 woman factory worker: dark skin tone
👩🏻‍🏭 woman factory worker: light skin tone
👩🏾‍🏭 woman factory worker: mediumdark skin tone
👩🏼‍🏭 woman factory worker: mediumlight skin tone
👩🏽‍🏭 woman factory worker: medium skin tone
👩‍🌾 woman farmer
👩🏿‍🌾 woman farmer: dark skin tone
👩🏻‍🌾 woman farmer: light skin tone
👩🏾‍🌾 woman farmer: mediumdark skin tone
👩🏼‍🌾 woman farmer: mediumlight skin tone
👩🏽‍🌾 woman farmer: medium skin tone
👩‍🚒 woman firefighter
👩🏿‍🚒 woman firefighter: dark skin tone
👩🏻‍🚒 woman firefighter: light skin tone
👩🏾‍🚒 woman firefighter: mediumdark skin tone
👩🏼‍🚒 woman firefighter: mediumlight skin tone
👩🏽‍🚒 woman firefighter: medium skin tone
🙍‍♀️ woman frowning
🙍🏿‍♀️ woman frowning: dark skin tone
🙍🏻‍♀️ woman frowning: light skin tone
🙍🏾‍♀️ woman frowning: mediumdark skin tone
🙍🏼‍♀️ woman frowning: mediumlight skin tone
🙍🏽‍♀️ woman frowning: medium skin tone
🙅‍♀️ woman gesturing NO
🙅🏿‍♀️ woman gesturing NO: dark skin tone
🙅🏻‍♀️ woman gesturing NO: light skin tone
🙅🏾‍♀️ woman gesturing NO: mediumdark skin tone
🙅🏼‍♀️ woman gesturing NO: mediumlight skin tone
🙅🏽‍♀️ woman gesturing NO: medium skin tone
🙆‍♀️ woman gesturing OK
🙆🏿‍♀️ woman gesturing OK: dark skin tone
🙆🏻‍♀️ woman gesturing OK: light skin tone
🙆🏾‍♀️ woman gesturing OK: mediumdark skin tone
🙆🏼‍♀️ woman gesturing OK: mediumlight skin tone
🙆🏽‍♀️ woman gesturing OK: medium skin tone
💇‍♀️ woman getting haircut
💇🏿‍♀️ woman getting haircut: dark skin tone
💇🏻‍♀️ woman getting haircut: light skin tone
💇🏾‍♀️ woman getting haircut: mediumdark skin tone
💇🏼‍♀️ woman getting haircut: mediumlight skin tone
💇🏽‍♀️ woman getting haircut: medium skin tone
💆‍♀️ woman getting massage
💆🏿‍♀️ woman getting massage: dark skin tone
💆🏻‍♀️ woman getting massage: light skin tone
💆🏾‍♀️ woman getting massage: mediumdark skin tone
💆🏼‍♀️ woman getting massage: mediumlight skin tone
💆🏽‍♀️ woman getting massage: medium skin tone
🏌️‍♀️ woman golfing
🏌🏿‍♀️ woman golfing: dark skin tone
🏌🏻‍♀️ woman golfing: light skin tone
🏌🏾‍♀️ woman golfing: mediumdark skin tone
🏌🏼‍♀️ woman golfing: mediumlight skin tone
🏌🏽‍♀️ woman golfing: medium skin tone
👩‍⚕️ woman health worker
👩🏿‍⚕ woman health worker: dark skin tone
👩🏻‍⚕ woman health worker: light skin tone
👩🏾‍⚕ woman health worker: mediumdark skin tone
👩🏼‍⚕ woman health worker: mediumlight skin tone
👩🏽‍⚕ woman health worker: medium skin tone
🧘‍♀️ woman in lotus position
🧘🏿‍♀️ woman in lotus position: dark skin tone
🧘🏻‍♀️ woman in lotus position: light skin tone
🧘🏾‍♀️ woman in lotus position: mediumdark skin tone
🧘🏼‍♀️ woman in lotus position: mediumlight skin tone
🧘🏽‍♀️ woman in lotus position: medium skin tone
🧖‍♀️ woman in steamy room
🧖🏿‍♀️ woman in steamy room: dark skin tone
🧖🏻‍♀️ woman in steamy room: light skin tone
🧖🏾‍♀️ woman in steamy room: mediumdark skin tone
🧖🏼‍♀️ woman in steamy room: mediumlight skin tone
🧖🏽‍♀️ woman in steamy room: medium skin tone
👩‍⚖️ woman judge
👩🏿‍⚖ woman judge: dark skin tone
👩🏻‍⚖ woman judge: light skin tone
👩🏾‍⚖ woman judge: mediumdark skin tone
👩🏼‍⚖ woman judge: mediumlight skin tone
👩🏽‍⚖ woman judge: medium skin tone
🤹‍♀️ woman juggling
🤹🏿‍♀️ woman juggling: dark skin tone
🤹🏻‍♀️ woman juggling: light skin tone
🤹🏾‍♀️ woman juggling: mediumdark skin tone
🤹🏼‍♀️ woman juggling: mediumlight skin tone
🤹🏽‍♀️ woman juggling: medium skin tone
🧎‍♀️ woman kneeling
🧎🏿‍♀️ woman kneeling: dark skin tone
🧎🏻‍♀️ woman kneeling: light skin tone
🧎🏾‍♀️ woman kneeling: mediumdark skin tone
🧎🏼‍♀️ woman kneeling: mediumlight skin tone
🧎🏽‍♀️ woman kneeling: medium skin tone
🏋️‍♀️ woman lifting weights
🏋🏿‍♀️ woman lifting weights: dark skin tone
🏋🏻‍♀️ woman lifting weights: light skin tone
🏋🏾‍♀️ woman lifting weights: mediumdark skin tone
🏋🏼‍♀️ woman lifting weights: mediumlight skin tone
🏋🏽‍♀️ woman lifting weights: medium skin tone
👩🏻 woman: light skin tone
👩‍🔧 woman mechanic
👩🏿‍🔧 woman mechanic: dark skin tone
👩🏻‍🔧 woman mechanic: light skin tone
👩🏾‍🔧 woman mechanic: mediumdark skin tone
👩🏼‍🔧 woman mechanic: mediumlight skin tone
👩🏽‍🔧 woman mechanic: medium skin tone
👩🏾 woman: mediumdark skin tone
👩🏼 woman: mediumlight skin tone
👩🏽 woman: medium skin tone
🚵‍♀️ woman mountain biking
🚵🏿‍♀️ woman mountain biking: dark skin tone
🚵🏻‍♀️ woman mountain biking: light skin tone
🚵🏾‍♀️ woman mountain biking: mediumdark skin tone
🚵🏼‍♀️ woman mountain biking: mediumlight skin tone
🚵🏽‍♀️ woman mountain biking: medium skin tone
👩‍💼 woman office worker
👩🏿‍💼 woman office worker: dark skin tone
👩🏻‍💼 woman office worker: light skin tone
👩🏾‍💼 woman office worker: mediumdark skin tone
👩🏼‍💼 woman office worker: mediumlight skin tone
👩🏽‍💼 woman office worker: medium skin tone
👩‍🦽 woman person in manual wheelchair
👩🏿‍🦽 woman person in manual wheelchair: dark skin tone
👩🏻‍🦽 woman person in manual wheelchair: light skin tone
👩🏾‍🦽 woman person in manual wheelchair: mediumdark skin tone
👩🏼‍🦽 woman person in manual wheelchair: mediumlight skin tone
👩🏽‍🦽 woman person in manual wheelchair: medium skin tone
👩‍🦼 woman person in motorized wheelchair
👩🏿‍🦼 woman person in motorized wheelchair: dark skin tone
👩🏻‍🦼 woman person in motorized wheelchair: light skin tone
👩🏾‍🦼 woman person in motorized wheelchair: mediumdark skin tone
👩🏼‍🦼 woman person in motorized wheelchair: mediumlight skin tone
👩🏽‍🦼 woman person in motorized wheelchair: medium skin tone
👩‍🦯 woman person with probing cane
👩🏿‍🦯 woman person with probing cane: dark skin tone
👩🏻‍🦯 woman person with probing cane: light skin tone
👩🏾‍🦯 woman person with probing cane: mediumdark skin tone
👩🏼‍🦯 woman person with probing cane: mediumlight skin tone
👩🏽‍🦯 woman person with probing cane: medium skin tone
👩‍✈️ woman pilot
👩🏿‍✈ woman pilot: dark skin tone
👩🏻‍✈ woman pilot: light skin tone
👩🏾‍✈ woman pilot: mediumdark skin tone
👩🏼‍✈ woman pilot: mediumlight skin tone
👩🏽‍✈ woman pilot: medium skin tone
🤾‍♀️ woman playing handball
🤾🏿‍♀️ woman playing handball: dark skin tone
🤾🏻‍♀️ woman playing handball: light skin tone
🤾🏾‍♀️ woman playing handball: mediumdark skin tone
🤾🏼‍♀️ woman playing handball: mediumlight skin tone
🤾🏽‍♀️ woman playing handball: medium skin tone
🤽‍♀️ woman playing water polo
🤽🏿‍♀️ woman playing water polo: dark skin tone
🤽🏻‍♀️ woman playing water polo: light skin tone
🤽🏾‍♀️ woman playing water polo: mediumdark skin tone
🤽🏼‍♀️ woman playing water polo: mediumlight skin tone
🤽🏽‍♀️ woman playing water polo: medium skin tone
🙎‍♀️ woman pouting
🙎🏿‍♀️ woman pouting: dark skin tone
🙎🏻‍♀️ woman pouting: light skin tone
🙎🏾‍♀️ woman pouting: mediumdark skin tone
🙎🏼‍♀️ woman pouting: mediumlight skin tone
🙎🏽‍♀️ woman pouting: medium skin tone
🙋‍♀️ woman raising hand
🙋🏿‍♀️ woman raising hand: dark skin tone
🙋🏻‍♀️ woman raising hand: light skin tone
🙋🏾‍♀️ woman raising hand: mediumdark skin tone
🙋🏼‍♀️ woman raising hand: mediumlight skin tone
🙋🏽‍♀️ woman raising hand: medium skin tone
👩‍🦰 woman: red hair
👩🏿‍🦰 woman: red hair: dark skin tone
👩🏻‍🦰 woman: red hair: light skin tone
👩🏾‍🦰 woman: red hair: mediumdark skin tone
👩🏼‍🦰 woman: red hair: mediumlight skin tone
👩🏽‍🦰 woman: red hair: medium skin tone
🚣‍♀️ woman rowing boat
🚣🏿‍♀️ woman rowing boat: dark skin tone
🚣🏻‍♀️ woman rowing boat: light skin tone
🚣🏾‍♀️ woman rowing boat: mediumdark skin tone
🚣🏼‍♀️ woman rowing boat: mediumlight skin tone
🚣🏽‍♀️ woman rowing boat: medium skin tone
🏃‍♀️ woman running
🏃🏿‍♀️ woman running: dark skin tone
🏃🏻‍♀️ woman running: light skin tone
🏃🏾‍♀️ woman running: mediumdark skin tone
🏃🏼‍♀️ woman running: mediumlight skin tone
🏃🏽‍♀️ woman running: medium skin tone
👢 woman’s boot
👩‍🔬 woman scientist
👩🏿‍🔬 woman scientist: dark skin tone
👩🏻‍🔬 woman scientist: light skin tone
👩🏾‍🔬 woman scientist: mediumdark skin tone
👩🏼‍🔬 woman scientist: mediumlight skin tone
👩🏽‍🔬 woman scientist: medium skin tone
👚 woman’s clothes
👒 woman’s hat
🤷‍♀️ woman shrugging
🤷🏿‍♀️ woman shrugging: dark skin tone
🤷🏻‍♀️ woman shrugging: light skin tone
🤷🏾‍♀️ woman shrugging: mediumdark skin tone
🤷🏼‍♀️ woman shrugging: mediumlight skin tone
🤷🏽‍♀️ woman shrugging: medium skin tone
👩‍🎤 woman singer
👩🏿‍🎤 woman singer: dark skin tone
👩🏻‍🎤 woman singer: light skin tone
👩🏾‍🎤 woman singer: mediumdark skin tone
👩🏼‍🎤 woman singer: mediumlight skin tone
👩🏽‍🎤 woman singer: medium skin tone
👡 woman’s sandal
🧍‍♀️ woman standing
🧍🏿‍♀️ woman standing: dark skin tone
🧍🏻‍♀️ woman standing: light skin tone
🧍🏾‍♀️ woman standing: mediumdark skin tone
🧍🏼‍♀️ woman standing: mediumlight skin tone
🧍🏽‍♀️ woman standing: medium skin tone
👩‍🎓 woman student
👩🏿‍🎓 woman student: dark skin tone
👩🏻‍🎓 woman student: light skin tone
👩🏾‍🎓 woman student: mediumdark skin tone
👩🏼‍🎓 woman student: mediumlight skin tone
👩🏽‍🎓 woman student: medium skin tone
🏄‍♀️ woman surfing
🏄🏿‍♀️ woman surfing: dark skin tone
🏄🏻‍♀️ woman surfing: light skin tone
🏄🏾‍♀️ woman surfing: mediumdark skin tone
🏄🏼‍♀️ woman surfing: mediumlight skin tone
🏄🏽‍♀️ woman surfing: medium skin tone
🏊‍♀️ woman swimming
🏊🏿‍♀️ woman swimming: dark skin tone
🏊🏻‍♀️ woman swimming: light skin tone
🏊🏾‍♀️ woman swimming: mediumdark skin tone
🏊🏼‍♀️ woman swimming: mediumlight skin tone
🏊🏽‍♀️ woman swimming: medium skin tone
👩‍🏫 woman teacher
👩🏿‍🏫 woman teacher: dark skin tone
👩🏻‍🏫 woman teacher: light skin tone
👩🏾‍🏫 woman teacher: mediumdark skin tone
👩🏼‍🏫 woman teacher: mediumlight skin tone
👩🏽‍🏫 woman teacher: medium skin tone
👩‍💻 woman technologist
👩🏿‍💻 woman technologist: dark skin tone
👩🏻‍💻 woman technologist: light skin tone
👩🏾‍💻 woman technologist: mediumdark skin tone
👩🏼‍💻 woman technologist: mediumlight skin tone
👩🏽‍💻 woman technologist: medium skin tone
💁‍♀️ woman tipping hand
💁🏿‍♀️ woman tipping hand: dark skin tone
💁🏻‍♀️ woman tipping hand: light skin tone
💁🏾‍♀️ woman tipping hand: mediumdark skin tone
💁🏼‍♀️ woman tipping hand: mediumlight skin tone
💁🏽‍♀️ woman tipping hand: medium skin tone
🚶‍♀️ woman walking
🚶🏿‍♀️ woman walking: dark skin tone
🚶🏻‍♀️ woman walking: light skin tone
🚶🏾‍♀️ woman walking: mediumdark skin tone
🚶🏼‍♀️ woman walking: mediumlight skin tone
🚶🏽‍♀️ woman walking: medium skin tone
👳‍♀️ woman wearing turban
👳🏿‍♀️ woman wearing turban: dark skin tone
👳🏻‍♀️ woman wearing turban: light skin tone
👳🏾‍♀️ woman wearing turban: mediumdark skin tone
👳🏼‍♀️ woman wearing turban: mediumlight skin tone
👳🏽‍♀️ woman wearing turban: medium skin tone
👩‍🦳 woman: white hair
👩🏿‍🦳 woman: white hair: dark skin tone
👩🏻‍🦳 woman: white hair: light skin tone
👩🏾‍🦳 woman: white hair: mediumdark skin tone
👩🏼‍🦳 woman: white hair: mediumlight skin tone
👩🏽‍🦳 woman: white hair: medium skin tone
🧕 woman with headscarf
🧕🏿 woman with headscarf: dark skin tone
🧕🏻 woman with headscarf: light skin tone
🧕🏾 woman with headscarf: mediumdark skin tone
🧕🏼 woman with headscarf: mediumlight skin tone
🧕🏽 woman with headscarf: medium skin tone
👭 women holding hands
🚺 women’s room
🥴 woozy face
🗺️ world map
😟 worried face
🎁 wrapped gift
🔧 wrench
✍️ writing hand
✍🏿 writing hand: dark skin tone
✍🏻 writing hand: light skin tone
✍🏾 writing hand: mediumdark skin tone
✍🏼 writing hand: mediumlight skin tone
✍🏽 writing hand: medium skin tone
🧶 yarn
🥱 yawning face
🟡 yellow circle
💛 yellow heart
🟨 yellow square
💴 yen banknote
☯️ yin yang
🪀 yo-yo
🤪 zany face
🦓 zebra
🤐 zipper-mouth face
🧟 zombie
🧟‍♂️ zombie
💤 zzz
ENDOFFUCKINGFILE
}

if [[ -z $m1 ]]; then
	echo ""
	echo "options: list grep fzf rofi dmenu" | grep --color=auto .
	echo "rofi or dmenu goes into xclip"
	echo ""
	echo "anyway, here's a random emoji:"
	echo ""
	listemoji | sort -R | head -n 1
	echo ""

elif [[ $m1 == "grep" ]]; then
	if [[ $m2 != "" ]]; then
        listemoji | grep -i --color=auto "$m2"
    else
		echo "maybe a search term?"
	fi

elif [[ $m1 == "list" ]]; then
	listemoji

elif [[ $m1 == "fzf" ]]; then
	listemoji | fzf

elif [[ $m1 == "rofi" ]]; then
	listemoji | rofi -dmenu -i |  xclip -selection clipboard -i
	

elif [[ $m1 == "dmenu" ]]; then
	listemoji | dmenu |  xclip -selection clipboard -i


elif [[ $m1 != "" ]]; then
	echo ""
	echo "Enter a more useful command, dipshit"
	echo ""
fi
